joint_map:
  # 1: leg_1_joint_1
  2: leg_1_joint_2
  1: leg_1_joint_3
  3: leg_2_joint_1
  4: leg_2_joint_2
  121: leg_2_joint_3
  5: leg_3_joint_1
  6: leg_3_joint_2
  122: leg_3_joint_3
  7: leg_4_joint_1
  8: leg_4_joint_2
  123: leg_4_joint_3
  

ecat_to_hal_id:
  1 : 2 #LF_haa
  2 : 1 #LF_hfe
  120 : 0 # LF_kfe, valve
  3 : 3 #RF_haa
  4 : 4 #RF_hfe
  121 : 5 #RF_kfe valve
  5 : 6 #LH_haa
  6 : 7 #LH_hfe
  122 : 8 #LH_kfe valve
  7 : 9 #RH_haa
  8 : 10 #RH_hfe
  123 : 11 #RH_kfe valve
  101: 101

id_to_name:
  0: "LF_haa"
  1: "LF_hfe"
  2: "LF_kfe"
  3: "RF_haa"
  4: "RF_hfe"
  5: "RF_kfe"
  6: "LH_haa"
  7: "LH_hfe"
  8: "LH_kfe"
  9: "RH_haa"
  10: "RH_hfe"
  11: "RH_kfe"