# [motor temp, motor angular vel, desired torque, compensation factor]
# motor temp: 20
# motor angular vel: 0
# desired torque: 20, 70, 130, -20, -70, -130
# 0: [20,   5,  20,    1, #LF_haa
#     20,   5,  70,    2,
#     20,   10,  20,   3,
#     20,   10,  70,   4,
#     30,   5,  20,   5,
#     30,   5,  70,  6,
#     30,   10, 20, 7,
#     30,   10, 70, 8]
1:  [] #LF_hfe
2:  [] # LF_kfe, valve
3:  [] #RF_haa
4:  [] #RF_hfe
5:  [] #RF_kfe valve
6:  [] #LH_haa
7:  [] #LH_hfe
8:  [] #LH_kfe valve
9:  [] #RH_haa
10: [] #RH_hfe
11: [] #RH_kfe valve


# advr
# 0: [20,   0,  5,    1.6,
#     20,   0,  20,    1.255,
#     20,   0,  70,    1.21,
#     20,   0,  100,   1.22,
#     20,   0,  130,   1.22,
#     20,   0,  -5,    1,
#     20,   0,  -20,   1.07,
#     20,   0,  -70,   1.17,
#     20,   0,  -100,   1.285,
#     20,   0,  -130,  1.29]

# circulo
0: [20,   0,  5,    0.9,
    20,   0,  10,    1.2,
    20,   0,  20,    1.05,
    20,   0,  70,    1.07,
    20,   0,  100,   1.11,
    20,   0,  130,   1.15,
    20,   0,  -5,    1.5,
    20,   0,  -10,    1.35,
    20,   0,  -20,   1.17,
    20,   0,  -70,   1.11,
    20,   0,  -100,  1.13,
    20,   0,  -130,  1.2]