// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ecat_control_refTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "ecat_control_refTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "ecat_control_ref.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_EcatControlRefMsg_type_identifier(
        TypeIdentifierPair& type_ids_EcatControlRefMsg)
{

    ReturnCode_t return_code_EcatControlRefMsg {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EcatControlRefMsg =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EcatControlRefMsg", type_ids_EcatControlRefMsg);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EcatControlRefMsg)
    {
        StructTypeFlag struct_flags_EcatControlRefMsg = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_EcatControlRefMsg = "EcatControlRefMsg";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EcatControlRefMsg;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EcatControlRefMsg;
        CompleteTypeDetail detail_EcatControlRefMsg = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EcatControlRefMsg, ann_custom_EcatControlRefMsg, type_name_EcatControlRefMsg.to_string());
        CompleteStructHeader header_EcatControlRefMsg;
        header_EcatControlRefMsg = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_EcatControlRefMsg);
        CompleteStructMemberSeq member_seq_EcatControlRefMsg;
        {
            TypeIdentifierPair type_ids_frame_id;
            ReturnCode_t return_code_frame_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_frame_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_frame_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_frame_id)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_frame_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_frame_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_frame_id = 0x00000000;
            bool common_frame_id_ec {false};
            CommonStructMember common_frame_id {TypeObjectUtils::build_common_struct_member(member_id_frame_id, member_flags_frame_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frame_id, common_frame_id_ec))};
            if (!common_frame_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure frame_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_frame_id = "frame_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_frame_id;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_frame_id = TypeObjectUtils::build_complete_member_detail(name_frame_id, member_ann_builtin_frame_id, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_frame_id = TypeObjectUtils::build_complete_struct_member(common_frame_id, detail_frame_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_frame_id);
        }
        {
            TypeIdentifierPair type_ids_sequence_id;
            ReturnCode_t return_code_sequence_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sequence_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_sequence_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sequence_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "sequence_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_sequence_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sequence_id = 0x00000001;
            bool common_sequence_id_ec {false};
            CommonStructMember common_sequence_id {TypeObjectUtils::build_common_struct_member(member_id_sequence_id, member_flags_sequence_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sequence_id, common_sequence_id_ec))};
            if (!common_sequence_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sequence_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sequence_id = "sequence_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sequence_id;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_sequence_id = TypeObjectUtils::build_complete_member_detail(name_sequence_id, member_ann_builtin_sequence_id, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_sequence_id = TypeObjectUtils::build_complete_struct_member(common_sequence_id, detail_sequence_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_sequence_id);
        }
        {
            TypeIdentifierPair type_ids_timestamp;
            ReturnCode_t return_code_timestamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_timestamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp = 0x00000002;
            bool common_timestamp_ec {false};
            CommonStructMember common_timestamp {TypeObjectUtils::build_common_struct_member(member_id_timestamp, member_flags_timestamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp, common_timestamp_ec))};
            if (!common_timestamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp = "timestamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_timestamp = TypeObjectUtils::build_complete_member_detail(name_timestamp, member_ann_builtin_timestamp, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_timestamp = TypeObjectUtils::build_complete_struct_member(common_timestamp, detail_timestamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_timestamp);
        }
        {
            TypeIdentifierPair type_ids_amplitude;
            ReturnCode_t return_code_amplitude {eprosima::fastdds::dds::RETCODE_OK};
            return_code_amplitude =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_amplitude);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_amplitude)
            {
                return_code_amplitude =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_amplitude);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_amplitude)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_amplitude, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_amplitude.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_amplitude))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_amplitude = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_amplitude = 0x00000003;
            bool common_amplitude_ec {false};
            CommonStructMember common_amplitude {TypeObjectUtils::build_common_struct_member(member_id_amplitude, member_flags_amplitude, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_amplitude, common_amplitude_ec))};
            if (!common_amplitude_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure amplitude member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_amplitude = "amplitude";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_amplitude;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_amplitude = TypeObjectUtils::build_complete_member_detail(name_amplitude, member_ann_builtin_amplitude, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_amplitude = TypeObjectUtils::build_complete_struct_member(common_amplitude, detail_amplitude);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_amplitude);
        }
        {
            TypeIdentifierPair type_ids_frequency;
            ReturnCode_t return_code_frequency {eprosima::fastdds::dds::RETCODE_OK};
            return_code_frequency =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_frequency);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_frequency)
            {
                return_code_frequency =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_frequency);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_frequency)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frequency, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_frequency.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_frequency))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_frequency = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_frequency = 0x00000004;
            bool common_frequency_ec {false};
            CommonStructMember common_frequency {TypeObjectUtils::build_common_struct_member(member_id_frequency, member_flags_frequency, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frequency, common_frequency_ec))};
            if (!common_frequency_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure frequency member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_frequency = "frequency";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_frequency;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_frequency = TypeObjectUtils::build_complete_member_detail(name_frequency, member_ann_builtin_frequency, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_frequency = TypeObjectUtils::build_complete_struct_member(common_frequency, detail_frequency);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_frequency);
        }
        {
            TypeIdentifierPair type_ids_offset;
            ReturnCode_t return_code_offset {eprosima::fastdds::dds::RETCODE_OK};
            return_code_offset =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_offset);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_offset)
            {
                return_code_offset =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_offset);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_offset)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_offset, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_offset.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_offset))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_offset = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_offset = 0x00000005;
            bool common_offset_ec {false};
            CommonStructMember common_offset {TypeObjectUtils::build_common_struct_member(member_id_offset, member_flags_offset, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_offset, common_offset_ec))};
            if (!common_offset_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure offset member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_offset = "offset";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_offset;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_offset = TypeObjectUtils::build_complete_member_detail(name_offset, member_ann_builtin_offset, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_offset = TypeObjectUtils::build_complete_struct_member(common_offset, detail_offset);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_offset);
        }
        {
            TypeIdentifierPair type_ids_traj_type;
            ReturnCode_t return_code_traj_type {eprosima::fastdds::dds::RETCODE_OK};
            return_code_traj_type =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_anonymous_string_unbounded_12", type_ids_traj_type);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_traj_type)
            {
                return_code_traj_type =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "anonymous_string_unbounded", type_ids_traj_type);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_traj_type)
                {
                    {
                        SBound bound = 0;
                        StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                                TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                                "anonymous_string_unbounded", type_ids_traj_type))
                        {
                            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                                "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                        }
                    }
                }
                bool element_identifier_anonymous_array_anonymous_string_unbounded_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_anonymous_string_unbounded_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_traj_type, element_identifier_anonymous_array_anonymous_string_unbounded_12_ec))};
                if (!element_identifier_anonymous_array_anonymous_string_unbounded_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_anonymous_string_unbounded_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_traj_type.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_anonymous_string_unbounded_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_anonymous_string_unbounded_12 = 0;
                PlainCollectionHeader header_anonymous_array_anonymous_string_unbounded_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_anonymous_string_unbounded_12, element_flags_anonymous_array_anonymous_string_unbounded_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_anonymous_string_unbounded_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_anonymous_string_unbounded_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_anonymous_string_unbounded_12", type_ids_traj_type))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_anonymous_string_unbounded_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_traj_type = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_traj_type = 0x00000006;
            bool common_traj_type_ec {false};
            CommonStructMember common_traj_type {TypeObjectUtils::build_common_struct_member(member_id_traj_type, member_flags_traj_type, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_traj_type, common_traj_type_ec))};
            if (!common_traj_type_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure traj_type member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_traj_type = "traj_type";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_traj_type;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_traj_type = TypeObjectUtils::build_complete_member_detail(name_traj_type, member_ann_builtin_traj_type, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_traj_type = TypeObjectUtils::build_complete_struct_member(common_traj_type, detail_traj_type);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_traj_type);
        }
        {
            TypeIdentifierPair type_ids_traj_mode;
            ReturnCode_t return_code_traj_mode {eprosima::fastdds::dds::RETCODE_OK};
            return_code_traj_mode =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_anonymous_string_unbounded_12", type_ids_traj_mode);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_traj_mode)
            {
                return_code_traj_mode =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "anonymous_string_unbounded", type_ids_traj_mode);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_traj_mode)
                {
                    {
                        SBound bound = 0;
                        StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                                TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                                "anonymous_string_unbounded", type_ids_traj_mode))
                        {
                            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                                "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                        }
                    }
                }
                bool element_identifier_anonymous_array_anonymous_string_unbounded_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_anonymous_string_unbounded_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_traj_mode, element_identifier_anonymous_array_anonymous_string_unbounded_12_ec))};
                if (!element_identifier_anonymous_array_anonymous_string_unbounded_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_anonymous_string_unbounded_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_traj_mode.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_anonymous_string_unbounded_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_anonymous_string_unbounded_12 = 0;
                PlainCollectionHeader header_anonymous_array_anonymous_string_unbounded_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_anonymous_string_unbounded_12, element_flags_anonymous_array_anonymous_string_unbounded_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_anonymous_string_unbounded_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_anonymous_string_unbounded_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_anonymous_string_unbounded_12", type_ids_traj_mode))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_anonymous_string_unbounded_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_traj_mode = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_traj_mode = 0x00000007;
            bool common_traj_mode_ec {false};
            CommonStructMember common_traj_mode {TypeObjectUtils::build_common_struct_member(member_id_traj_mode, member_flags_traj_mode, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_traj_mode, common_traj_mode_ec))};
            if (!common_traj_mode_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure traj_mode member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_traj_mode = "traj_mode";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_traj_mode;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_traj_mode = TypeObjectUtils::build_complete_member_detail(name_traj_mode, member_ann_builtin_traj_mode, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_traj_mode = TypeObjectUtils::build_complete_struct_member(common_traj_mode, detail_traj_mode);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_traj_mode);
        }
        {
            TypeIdentifierPair type_ids_start_traj;
            ReturnCode_t return_code_start_traj {eprosima::fastdds::dds::RETCODE_OK};
            return_code_start_traj =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_bool_12", type_ids_start_traj);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_start_traj)
            {
                return_code_start_traj =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_bool", type_ids_start_traj);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_start_traj)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_bool_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_bool_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_start_traj, element_identifier_anonymous_array_bool_12_ec))};
                if (!element_identifier_anonymous_array_bool_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_bool_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_start_traj.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_bool_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_bool_12 = 0;
                PlainCollectionHeader header_anonymous_array_bool_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_bool_12, element_flags_anonymous_array_bool_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_bool_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_bool_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_bool_12", type_ids_start_traj))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_bool_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_start_traj = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_start_traj = 0x00000008;
            bool common_start_traj_ec {false};
            CommonStructMember common_start_traj {TypeObjectUtils::build_common_struct_member(member_id_start_traj, member_flags_start_traj, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_start_traj, common_start_traj_ec))};
            if (!common_start_traj_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure start_traj member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_start_traj = "start_traj";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_start_traj;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_start_traj = TypeObjectUtils::build_complete_member_detail(name_start_traj, member_ann_builtin_start_traj, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_start_traj = TypeObjectUtils::build_complete_struct_member(common_start_traj, detail_start_traj);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_start_traj);
        }
        {
            TypeIdentifierPair type_ids_max_freq;
            ReturnCode_t return_code_max_freq {eprosima::fastdds::dds::RETCODE_OK};
            return_code_max_freq =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_max_freq);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_max_freq)
            {
                return_code_max_freq =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_max_freq);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_max_freq)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_max_freq, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_max_freq.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_max_freq))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_max_freq = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_max_freq = 0x00000009;
            bool common_max_freq_ec {false};
            CommonStructMember common_max_freq {TypeObjectUtils::build_common_struct_member(member_id_max_freq, member_flags_max_freq, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_max_freq, common_max_freq_ec))};
            if (!common_max_freq_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure max_freq member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_max_freq = "max_freq";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_max_freq;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_max_freq = TypeObjectUtils::build_complete_member_detail(name_max_freq, member_ann_builtin_max_freq, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_max_freq = TypeObjectUtils::build_complete_struct_member(common_max_freq, detail_max_freq);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_max_freq);
        }
        {
            TypeIdentifierPair type_ids_torque_scale_factor;
            ReturnCode_t return_code_torque_scale_factor {eprosima::fastdds::dds::RETCODE_OK};
            return_code_torque_scale_factor =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_torque_scale_factor);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque_scale_factor)
            {
                return_code_torque_scale_factor =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_torque_scale_factor);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque_scale_factor)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque_scale_factor, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_torque_scale_factor.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_torque_scale_factor))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_torque_scale_factor = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_torque_scale_factor = 0x0000000a;
            bool common_torque_scale_factor_ec {false};
            CommonStructMember common_torque_scale_factor {TypeObjectUtils::build_common_struct_member(member_id_torque_scale_factor, member_flags_torque_scale_factor, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque_scale_factor, common_torque_scale_factor_ec))};
            if (!common_torque_scale_factor_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure torque_scale_factor member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_torque_scale_factor = "torque_scale_factor";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_torque_scale_factor;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_torque_scale_factor = TypeObjectUtils::build_complete_member_detail(name_torque_scale_factor, member_ann_builtin_torque_scale_factor, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_torque_scale_factor = TypeObjectUtils::build_complete_struct_member(common_torque_scale_factor, detail_torque_scale_factor);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_torque_scale_factor);
        }
        {
            TypeIdentifierPair type_ids_kp_torque;
            ReturnCode_t return_code_kp_torque {eprosima::fastdds::dds::RETCODE_OK};
            return_code_kp_torque =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_kp_torque);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_kp_torque)
            {
                return_code_kp_torque =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_kp_torque);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_kp_torque)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kp_torque, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_kp_torque.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_kp_torque))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_kp_torque = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_kp_torque = 0x0000000b;
            bool common_kp_torque_ec {false};
            CommonStructMember common_kp_torque {TypeObjectUtils::build_common_struct_member(member_id_kp_torque, member_flags_kp_torque, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kp_torque, common_kp_torque_ec))};
            if (!common_kp_torque_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure kp_torque member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_kp_torque = "kp_torque";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_kp_torque;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_kp_torque = TypeObjectUtils::build_complete_member_detail(name_kp_torque, member_ann_builtin_kp_torque, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_kp_torque = TypeObjectUtils::build_complete_struct_member(common_kp_torque, detail_kp_torque);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_kp_torque);
        }
        {
            TypeIdentifierPair type_ids_ki_torque;
            ReturnCode_t return_code_ki_torque {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ki_torque =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_ki_torque);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ki_torque)
            {
                return_code_ki_torque =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_ki_torque);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_ki_torque)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ki_torque, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_ki_torque.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_ki_torque))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_ki_torque = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ki_torque = 0x0000000c;
            bool common_ki_torque_ec {false};
            CommonStructMember common_ki_torque {TypeObjectUtils::build_common_struct_member(member_id_ki_torque, member_flags_ki_torque, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ki_torque, common_ki_torque_ec))};
            if (!common_ki_torque_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ki_torque member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ki_torque = "ki_torque";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ki_torque;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_ki_torque = TypeObjectUtils::build_complete_member_detail(name_ki_torque, member_ann_builtin_ki_torque, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_ki_torque = TypeObjectUtils::build_complete_struct_member(common_ki_torque, detail_ki_torque);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_ki_torque);
        }
        {
            TypeIdentifierPair type_ids_kd_torque;
            ReturnCode_t return_code_kd_torque {eprosima::fastdds::dds::RETCODE_OK};
            return_code_kd_torque =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_kd_torque);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_kd_torque)
            {
                return_code_kd_torque =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_kd_torque);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_kd_torque)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kd_torque, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_kd_torque.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_kd_torque))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_kd_torque = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_kd_torque = 0x0000000d;
            bool common_kd_torque_ec {false};
            CommonStructMember common_kd_torque {TypeObjectUtils::build_common_struct_member(member_id_kd_torque, member_flags_kd_torque, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kd_torque, common_kd_torque_ec))};
            if (!common_kd_torque_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure kd_torque member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_kd_torque = "kd_torque";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_kd_torque;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_kd_torque = TypeObjectUtils::build_complete_member_detail(name_kd_torque, member_ann_builtin_kd_torque, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_kd_torque = TypeObjectUtils::build_complete_struct_member(common_kd_torque, detail_kd_torque);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_kd_torque);
        }
        {
            TypeIdentifierPair type_ids_kp_position;
            ReturnCode_t return_code_kp_position {eprosima::fastdds::dds::RETCODE_OK};
            return_code_kp_position =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_kp_position);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_kp_position)
            {
                return_code_kp_position =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_kp_position);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_kp_position)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kp_position, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_kp_position.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_kp_position))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_kp_position = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_kp_position = 0x0000000e;
            bool common_kp_position_ec {false};
            CommonStructMember common_kp_position {TypeObjectUtils::build_common_struct_member(member_id_kp_position, member_flags_kp_position, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kp_position, common_kp_position_ec))};
            if (!common_kp_position_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure kp_position member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_kp_position = "kp_position";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_kp_position;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_kp_position = TypeObjectUtils::build_complete_member_detail(name_kp_position, member_ann_builtin_kp_position, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_kp_position = TypeObjectUtils::build_complete_struct_member(common_kp_position, detail_kp_position);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_kp_position);
        }
        {
            TypeIdentifierPair type_ids_ki_position;
            ReturnCode_t return_code_ki_position {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ki_position =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_ki_position);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ki_position)
            {
                return_code_ki_position =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_ki_position);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_ki_position)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ki_position, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_ki_position.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_ki_position))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_ki_position = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ki_position = 0x0000000f;
            bool common_ki_position_ec {false};
            CommonStructMember common_ki_position {TypeObjectUtils::build_common_struct_member(member_id_ki_position, member_flags_ki_position, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ki_position, common_ki_position_ec))};
            if (!common_ki_position_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ki_position member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ki_position = "ki_position";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ki_position;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_ki_position = TypeObjectUtils::build_complete_member_detail(name_ki_position, member_ann_builtin_ki_position, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_ki_position = TypeObjectUtils::build_complete_struct_member(common_ki_position, detail_ki_position);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_ki_position);
        }
        {
            TypeIdentifierPair type_ids_kd_position;
            ReturnCode_t return_code_kd_position {eprosima::fastdds::dds::RETCODE_OK};
            return_code_kd_position =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_kd_position);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_kd_position)
            {
                return_code_kd_position =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_kd_position);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_kd_position)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kd_position, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_kd_position.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_kd_position))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_kd_position = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_kd_position = 0x00000010;
            bool common_kd_position_ec {false};
            CommonStructMember common_kd_position {TypeObjectUtils::build_common_struct_member(member_id_kd_position, member_flags_kd_position, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kd_position, common_kd_position_ec))};
            if (!common_kd_position_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure kd_position member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_kd_position = "kd_position";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_kd_position;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_kd_position = TypeObjectUtils::build_complete_member_detail(name_kd_position, member_ann_builtin_kd_position, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_kd_position = TypeObjectUtils::build_complete_struct_member(common_kd_position, detail_kd_position);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_kd_position);
        }
        {
            TypeIdentifierPair type_ids_current_offset;
            ReturnCode_t return_code_current_offset {eprosima::fastdds::dds::RETCODE_OK};
            return_code_current_offset =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_current_offset);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_current_offset)
            {
                return_code_current_offset =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_current_offset);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_current_offset)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current_offset, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_current_offset.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_current_offset))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_current_offset = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_current_offset = 0x00000011;
            bool common_current_offset_ec {false};
            CommonStructMember common_current_offset {TypeObjectUtils::build_common_struct_member(member_id_current_offset, member_flags_current_offset, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current_offset, common_current_offset_ec))};
            if (!common_current_offset_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure current_offset member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_current_offset = "current_offset";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_current_offset;
            ann_custom_EcatControlRefMsg.reset();
            CompleteMemberDetail detail_current_offset = TypeObjectUtils::build_complete_member_detail(name_current_offset, member_ann_builtin_current_offset, ann_custom_EcatControlRefMsg);
            CompleteStructMember member_current_offset = TypeObjectUtils::build_complete_struct_member(common_current_offset, detail_current_offset);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatControlRefMsg, member_current_offset);
        }
        CompleteStructType struct_type_EcatControlRefMsg = TypeObjectUtils::build_complete_struct_type(struct_flags_EcatControlRefMsg, header_EcatControlRefMsg, member_seq_EcatControlRefMsg);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_EcatControlRefMsg, type_name_EcatControlRefMsg.to_string(), type_ids_EcatControlRefMsg))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "EcatControlRefMsg already registered in TypeObjectRegistry for a different type.");
        }
    }
}

