// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ecat_control_refTypeObject.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "ecat_control_ref.h"
#include "ecat_control_refTypeObject.h"
#include <mutex>
#include <utility>
#include <sstream>
#include <fastrtps/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>
#include <fastrtps/types/TypeObjectFactory.h>
#include <fastrtps/types/TypeNamesGenerator.h>
#include <fastrtps/types/AnnotationParameterValue.h>
#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

using namespace eprosima::fastrtps::rtps;

void registerecat_control_refTypes()
{
    static std::once_flag once_flag;
    std::call_once(once_flag, []()
            {
                TypeObjectFactory *factory = TypeObjectFactory::get_instance();
                factory->add_type_object("EcatControlRefMsg", GetEcatControlRefMsgIdentifier(true),
                GetEcatControlRefMsgObject(true));
                factory->add_type_object("EcatControlRefMsg", GetEcatControlRefMsgIdentifier(false),
                GetEcatControlRefMsgObject(false));

            });
}

const TypeIdentifier* GetEcatControlRefMsgIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("EcatControlRefMsg", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetEcatControlRefMsgObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("EcatControlRefMsg", complete);
}

const TypeObject* GetEcatControlRefMsgObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("EcatControlRefMsg", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteEcatControlRefMsgObject();
    }
    //else
    return GetMinimalEcatControlRefMsgObject();
}

const TypeObject* GetMinimalEcatControlRefMsgObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("EcatControlRefMsg", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_frame_id;
    mst_frame_id.common().member_id(memberId++);
    mst_frame_id.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_frame_id.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_frame_id.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_frame_id.common().member_flags().IS_OPTIONAL(false);
    mst_frame_id.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_frame_id.common().member_flags().IS_KEY(false);
    mst_frame_id.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_frame_id.common().member_type_id(*TypeObjectFactory::get_instance()->get_string_identifier(255, false));


    MD5 frame_id_hash("frame_id");
    for(int i = 0; i < 4; ++i)
    {
        mst_frame_id.detail().name_hash()[i] = frame_id_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_frame_id);

    MinimalStructMember mst_sequence_id;
    mst_sequence_id.common().member_id(memberId++);
    mst_sequence_id.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_sequence_id.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_sequence_id.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_sequence_id.common().member_flags().IS_OPTIONAL(false);
    mst_sequence_id.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_sequence_id.common().member_flags().IS_KEY(false);
    mst_sequence_id.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_sequence_id.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint32_t", false));

    MD5 sequence_id_hash("sequence_id");
    for(int i = 0; i < 4; ++i)
    {
        mst_sequence_id.detail().name_hash()[i] = sequence_id_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_sequence_id);

    MinimalStructMember mst_timestamp;
    mst_timestamp.common().member_id(memberId++);
    mst_timestamp.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_timestamp.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_timestamp.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_timestamp.common().member_flags().IS_OPTIONAL(false);
    mst_timestamp.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_timestamp.common().member_flags().IS_KEY(false);
    mst_timestamp.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_timestamp.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 timestamp_hash("timestamp");
    for(int i = 0; i < 4; ++i)
    {
        mst_timestamp.detail().name_hash()[i] = timestamp_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_timestamp);

    MinimalStructMember mst_amplitude;
    mst_amplitude.common().member_id(memberId++);
    mst_amplitude.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_amplitude.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_amplitude.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_amplitude.common().member_flags().IS_OPTIONAL(false);
    mst_amplitude.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_amplitude.common().member_flags().IS_KEY(false);
    mst_amplitude.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_amplitude.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 amplitude_hash("amplitude");
    for(int i = 0; i < 4; ++i)
    {
        mst_amplitude.detail().name_hash()[i] = amplitude_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_amplitude);

    MinimalStructMember mst_frequency;
    mst_frequency.common().member_id(memberId++);
    mst_frequency.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_frequency.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_frequency.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_frequency.common().member_flags().IS_OPTIONAL(false);
    mst_frequency.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_frequency.common().member_flags().IS_KEY(false);
    mst_frequency.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_frequency.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 frequency_hash("frequency");
    for(int i = 0; i < 4; ++i)
    {
        mst_frequency.detail().name_hash()[i] = frequency_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_frequency);

    MinimalStructMember mst_offset;
    mst_offset.common().member_id(memberId++);
    mst_offset.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_offset.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_offset.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_offset.common().member_flags().IS_OPTIONAL(false);
    mst_offset.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_offset.common().member_flags().IS_KEY(false);
    mst_offset.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_offset.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 offset_hash("offset");
    for(int i = 0; i < 4; ++i)
    {
        mst_offset.detail().name_hash()[i] = offset_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_offset);

    MinimalStructMember mst_traj_type;
    mst_traj_type.common().member_id(memberId++);
    mst_traj_type.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_traj_type.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_traj_type.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_traj_type.common().member_flags().IS_OPTIONAL(false);
    mst_traj_type.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_traj_type.common().member_flags().IS_KEY(false);
    mst_traj_type.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_traj_type.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier(TypeNamesGenerator::get_string_type_name(255, false), {12}, false));


    MD5 traj_type_hash("traj_type");
    for(int i = 0; i < 4; ++i)
    {
        mst_traj_type.detail().name_hash()[i] = traj_type_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_traj_type);

    MinimalStructMember mst_traj_mode;
    mst_traj_mode.common().member_id(memberId++);
    mst_traj_mode.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_traj_mode.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_traj_mode.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_traj_mode.common().member_flags().IS_OPTIONAL(false);
    mst_traj_mode.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_traj_mode.common().member_flags().IS_KEY(false);
    mst_traj_mode.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_traj_mode.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier(TypeNamesGenerator::get_string_type_name(255, false), {12}, false));


    MD5 traj_mode_hash("traj_mode");
    for(int i = 0; i < 4; ++i)
    {
        mst_traj_mode.detail().name_hash()[i] = traj_mode_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_traj_mode);

    MinimalStructMember mst_start_traj;
    mst_start_traj.common().member_id(memberId++);
    mst_start_traj.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_start_traj.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_start_traj.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_start_traj.common().member_flags().IS_OPTIONAL(false);
    mst_start_traj.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_start_traj.common().member_flags().IS_KEY(false);
    mst_start_traj.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_start_traj.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("bool", {12}, false));


    MD5 start_traj_hash("start_traj");
    for(int i = 0; i < 4; ++i)
    {
        mst_start_traj.detail().name_hash()[i] = start_traj_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_start_traj);

    MinimalStructMember mst_max_freq;
    mst_max_freq.common().member_id(memberId++);
    mst_max_freq.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_max_freq.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_max_freq.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_max_freq.common().member_flags().IS_OPTIONAL(false);
    mst_max_freq.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_max_freq.common().member_flags().IS_KEY(false);
    mst_max_freq.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_max_freq.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 max_freq_hash("max_freq");
    for(int i = 0; i < 4; ++i)
    {
        mst_max_freq.detail().name_hash()[i] = max_freq_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_max_freq);

    MinimalStructMember mst_torque_scale_factor;
    mst_torque_scale_factor.common().member_id(memberId++);
    mst_torque_scale_factor.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_torque_scale_factor.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_torque_scale_factor.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_torque_scale_factor.common().member_flags().IS_OPTIONAL(false);
    mst_torque_scale_factor.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_torque_scale_factor.common().member_flags().IS_KEY(false);
    mst_torque_scale_factor.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_torque_scale_factor.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 torque_scale_factor_hash("torque_scale_factor");
    for(int i = 0; i < 4; ++i)
    {
        mst_torque_scale_factor.detail().name_hash()[i] = torque_scale_factor_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_torque_scale_factor);

    MinimalStructMember mst_kp_torque;
    mst_kp_torque.common().member_id(memberId++);
    mst_kp_torque.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_kp_torque.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_kp_torque.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_kp_torque.common().member_flags().IS_OPTIONAL(false);
    mst_kp_torque.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_kp_torque.common().member_flags().IS_KEY(false);
    mst_kp_torque.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_kp_torque.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 kp_torque_hash("kp_torque");
    for(int i = 0; i < 4; ++i)
    {
        mst_kp_torque.detail().name_hash()[i] = kp_torque_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_kp_torque);

    MinimalStructMember mst_ki_torque;
    mst_ki_torque.common().member_id(memberId++);
    mst_ki_torque.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_ki_torque.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_ki_torque.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_ki_torque.common().member_flags().IS_OPTIONAL(false);
    mst_ki_torque.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_ki_torque.common().member_flags().IS_KEY(false);
    mst_ki_torque.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_ki_torque.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 ki_torque_hash("ki_torque");
    for(int i = 0; i < 4; ++i)
    {
        mst_ki_torque.detail().name_hash()[i] = ki_torque_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_ki_torque);

    MinimalStructMember mst_kd_torque;
    mst_kd_torque.common().member_id(memberId++);
    mst_kd_torque.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_kd_torque.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_kd_torque.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_kd_torque.common().member_flags().IS_OPTIONAL(false);
    mst_kd_torque.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_kd_torque.common().member_flags().IS_KEY(false);
    mst_kd_torque.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_kd_torque.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 kd_torque_hash("kd_torque");
    for(int i = 0; i < 4; ++i)
    {
        mst_kd_torque.detail().name_hash()[i] = kd_torque_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_kd_torque);

    MinimalStructMember mst_kp_position;
    mst_kp_position.common().member_id(memberId++);
    mst_kp_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_kp_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_kp_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_kp_position.common().member_flags().IS_OPTIONAL(false);
    mst_kp_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_kp_position.common().member_flags().IS_KEY(false);
    mst_kp_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_kp_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 kp_position_hash("kp_position");
    for(int i = 0; i < 4; ++i)
    {
        mst_kp_position.detail().name_hash()[i] = kp_position_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_kp_position);

    MinimalStructMember mst_ki_position;
    mst_ki_position.common().member_id(memberId++);
    mst_ki_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_ki_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_ki_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_ki_position.common().member_flags().IS_OPTIONAL(false);
    mst_ki_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_ki_position.common().member_flags().IS_KEY(false);
    mst_ki_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_ki_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 ki_position_hash("ki_position");
    for(int i = 0; i < 4; ++i)
    {
        mst_ki_position.detail().name_hash()[i] = ki_position_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_ki_position);

    MinimalStructMember mst_kd_position;
    mst_kd_position.common().member_id(memberId++);
    mst_kd_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_kd_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_kd_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_kd_position.common().member_flags().IS_OPTIONAL(false);
    mst_kd_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_kd_position.common().member_flags().IS_KEY(false);
    mst_kd_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_kd_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 kd_position_hash("kd_position");
    for(int i = 0; i < 4; ++i)
    {
        mst_kd_position.detail().name_hash()[i] = kd_position_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_kd_position);

    MinimalStructMember mst_current_offset;
    mst_current_offset.common().member_id(memberId++);
    mst_current_offset.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_current_offset.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_current_offset.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_current_offset.common().member_flags().IS_OPTIONAL(false);
    mst_current_offset.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_current_offset.common().member_flags().IS_KEY(false);
    mst_current_offset.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_current_offset.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, false));


    MD5 current_offset_hash("current_offset");
    for(int i = 0; i < 4; ++i)
    {
        mst_current_offset.detail().name_hash()[i] = current_offset_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_current_offset);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("EcatControlRefMsg", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("EcatControlRefMsg", false);
}

const TypeObject* GetCompleteEcatControlRefMsgObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("EcatControlRefMsg", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_frame_id;
    cst_frame_id.common().member_id(memberId++);
    cst_frame_id.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_frame_id.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_frame_id.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_frame_id.common().member_flags().IS_OPTIONAL(false);
    cst_frame_id.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_frame_id.common().member_flags().IS_KEY(false);
    cst_frame_id.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_frame_id.common().member_type_id(*TypeObjectFactory::get_instance()->get_string_identifier(255, false));


    cst_frame_id.detail().name("frame_id");

    type_object->complete().struct_type().member_seq().emplace_back(cst_frame_id);

    CompleteStructMember cst_sequence_id;
    cst_sequence_id.common().member_id(memberId++);
    cst_sequence_id.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_sequence_id.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_sequence_id.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_sequence_id.common().member_flags().IS_OPTIONAL(false);
    cst_sequence_id.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_sequence_id.common().member_flags().IS_KEY(false);
    cst_sequence_id.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_sequence_id.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint32_t", false));

    cst_sequence_id.detail().name("sequence_id");

    type_object->complete().struct_type().member_seq().emplace_back(cst_sequence_id);

    CompleteStructMember cst_timestamp;
    cst_timestamp.common().member_id(memberId++);
    cst_timestamp.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_timestamp.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_timestamp.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_timestamp.common().member_flags().IS_OPTIONAL(false);
    cst_timestamp.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_timestamp.common().member_flags().IS_KEY(false);
    cst_timestamp.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_timestamp.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_timestamp.detail().name("timestamp");

    type_object->complete().struct_type().member_seq().emplace_back(cst_timestamp);

    CompleteStructMember cst_amplitude;
    cst_amplitude.common().member_id(memberId++);
    cst_amplitude.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_amplitude.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_amplitude.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_amplitude.common().member_flags().IS_OPTIONAL(false);
    cst_amplitude.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_amplitude.common().member_flags().IS_KEY(false);
    cst_amplitude.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_amplitude.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_amplitude.detail().name("amplitude");

    type_object->complete().struct_type().member_seq().emplace_back(cst_amplitude);

    CompleteStructMember cst_frequency;
    cst_frequency.common().member_id(memberId++);
    cst_frequency.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_frequency.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_frequency.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_frequency.common().member_flags().IS_OPTIONAL(false);
    cst_frequency.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_frequency.common().member_flags().IS_KEY(false);
    cst_frequency.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_frequency.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_frequency.detail().name("frequency");

    type_object->complete().struct_type().member_seq().emplace_back(cst_frequency);

    CompleteStructMember cst_offset;
    cst_offset.common().member_id(memberId++);
    cst_offset.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_offset.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_offset.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_offset.common().member_flags().IS_OPTIONAL(false);
    cst_offset.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_offset.common().member_flags().IS_KEY(false);
    cst_offset.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_offset.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_offset.detail().name("offset");

    type_object->complete().struct_type().member_seq().emplace_back(cst_offset);

    CompleteStructMember cst_traj_type;
    cst_traj_type.common().member_id(memberId++);
    cst_traj_type.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_traj_type.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_traj_type.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_traj_type.common().member_flags().IS_OPTIONAL(false);
    cst_traj_type.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_traj_type.common().member_flags().IS_KEY(false);
    cst_traj_type.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_traj_type.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier(TypeNamesGenerator::get_string_type_name(255, false), {12}, true));


    cst_traj_type.detail().name("traj_type");

    type_object->complete().struct_type().member_seq().emplace_back(cst_traj_type);

    CompleteStructMember cst_traj_mode;
    cst_traj_mode.common().member_id(memberId++);
    cst_traj_mode.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_traj_mode.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_traj_mode.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_traj_mode.common().member_flags().IS_OPTIONAL(false);
    cst_traj_mode.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_traj_mode.common().member_flags().IS_KEY(false);
    cst_traj_mode.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_traj_mode.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier(TypeNamesGenerator::get_string_type_name(255, false), {12}, true));


    cst_traj_mode.detail().name("traj_mode");

    type_object->complete().struct_type().member_seq().emplace_back(cst_traj_mode);

    CompleteStructMember cst_start_traj;
    cst_start_traj.common().member_id(memberId++);
    cst_start_traj.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_start_traj.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_start_traj.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_start_traj.common().member_flags().IS_OPTIONAL(false);
    cst_start_traj.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_start_traj.common().member_flags().IS_KEY(false);
    cst_start_traj.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_start_traj.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("bool", {12}, true));


    cst_start_traj.detail().name("start_traj");

    type_object->complete().struct_type().member_seq().emplace_back(cst_start_traj);

    CompleteStructMember cst_max_freq;
    cst_max_freq.common().member_id(memberId++);
    cst_max_freq.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_max_freq.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_max_freq.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_max_freq.common().member_flags().IS_OPTIONAL(false);
    cst_max_freq.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_max_freq.common().member_flags().IS_KEY(false);
    cst_max_freq.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_max_freq.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_max_freq.detail().name("max_freq");

    type_object->complete().struct_type().member_seq().emplace_back(cst_max_freq);

    CompleteStructMember cst_torque_scale_factor;
    cst_torque_scale_factor.common().member_id(memberId++);
    cst_torque_scale_factor.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_torque_scale_factor.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_torque_scale_factor.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_torque_scale_factor.common().member_flags().IS_OPTIONAL(false);
    cst_torque_scale_factor.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_torque_scale_factor.common().member_flags().IS_KEY(false);
    cst_torque_scale_factor.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_torque_scale_factor.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_torque_scale_factor.detail().name("torque_scale_factor");

    type_object->complete().struct_type().member_seq().emplace_back(cst_torque_scale_factor);

    CompleteStructMember cst_kp_torque;
    cst_kp_torque.common().member_id(memberId++);
    cst_kp_torque.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_kp_torque.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_kp_torque.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_kp_torque.common().member_flags().IS_OPTIONAL(false);
    cst_kp_torque.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_kp_torque.common().member_flags().IS_KEY(false);
    cst_kp_torque.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_kp_torque.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_kp_torque.detail().name("kp_torque");

    type_object->complete().struct_type().member_seq().emplace_back(cst_kp_torque);

    CompleteStructMember cst_ki_torque;
    cst_ki_torque.common().member_id(memberId++);
    cst_ki_torque.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_ki_torque.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_ki_torque.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_ki_torque.common().member_flags().IS_OPTIONAL(false);
    cst_ki_torque.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_ki_torque.common().member_flags().IS_KEY(false);
    cst_ki_torque.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_ki_torque.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_ki_torque.detail().name("ki_torque");

    type_object->complete().struct_type().member_seq().emplace_back(cst_ki_torque);

    CompleteStructMember cst_kd_torque;
    cst_kd_torque.common().member_id(memberId++);
    cst_kd_torque.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_kd_torque.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_kd_torque.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_kd_torque.common().member_flags().IS_OPTIONAL(false);
    cst_kd_torque.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_kd_torque.common().member_flags().IS_KEY(false);
    cst_kd_torque.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_kd_torque.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_kd_torque.detail().name("kd_torque");

    type_object->complete().struct_type().member_seq().emplace_back(cst_kd_torque);

    CompleteStructMember cst_kp_position;
    cst_kp_position.common().member_id(memberId++);
    cst_kp_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_kp_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_kp_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_kp_position.common().member_flags().IS_OPTIONAL(false);
    cst_kp_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_kp_position.common().member_flags().IS_KEY(false);
    cst_kp_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_kp_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_kp_position.detail().name("kp_position");

    type_object->complete().struct_type().member_seq().emplace_back(cst_kp_position);

    CompleteStructMember cst_ki_position;
    cst_ki_position.common().member_id(memberId++);
    cst_ki_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_ki_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_ki_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_ki_position.common().member_flags().IS_OPTIONAL(false);
    cst_ki_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_ki_position.common().member_flags().IS_KEY(false);
    cst_ki_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_ki_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_ki_position.detail().name("ki_position");

    type_object->complete().struct_type().member_seq().emplace_back(cst_ki_position);

    CompleteStructMember cst_kd_position;
    cst_kd_position.common().member_id(memberId++);
    cst_kd_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_kd_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_kd_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_kd_position.common().member_flags().IS_OPTIONAL(false);
    cst_kd_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_kd_position.common().member_flags().IS_KEY(false);
    cst_kd_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_kd_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_kd_position.detail().name("kd_position");

    type_object->complete().struct_type().member_seq().emplace_back(cst_kd_position);

    CompleteStructMember cst_current_offset;
    cst_current_offset.common().member_id(memberId++);
    cst_current_offset.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_current_offset.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_current_offset.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_current_offset.common().member_flags().IS_OPTIONAL(false);
    cst_current_offset.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_current_offset.common().member_flags().IS_KEY(false);
    cst_current_offset.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_current_offset.common().member_type_id(*TypeObjectFactory::get_instance()->get_array_identifier("double", {12}, true));


    cst_current_offset.detail().name("current_offset");

    type_object->complete().struct_type().member_seq().emplace_back(cst_current_offset);


    // Header
    type_object->complete().struct_type().header().detail().type_name("EcatControlRefMsg");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("EcatControlRefMsg", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("EcatControlRefMsg", true);
}
