// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ecat_robot_stateCdrAux.ipp
 * This source file contains some declarations of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__ECAT_ROBOT_STATECDRAUX_IPP
#define FAST_DDS_GENERATED__ECAT_ROBOT_STATECDRAUX_IPP

#include "ecat_robot_stateCdrAux.hpp"

#include <fastcdr/Cdr.h>
#include <fastcdr/CdrSizeCalculator.hpp>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

namespace eprosima {
namespace fastcdr {

template<>
eProsima_user_DllExport size_t calculate_serialized_size(
        eprosima::fastcdr::CdrSizeCalculator& calculator,
        const EcatRobotStateMsg& data,
        size_t& current_alignment)
{
    static_cast<void>(data);

    eprosima::fastcdr::EncodingAlgorithmFlag previous_encoding = calculator.get_encoding();
    size_t calculated_size {calculator.begin_calculate_type_serialized_size(
                                eprosima::fastcdr::CdrVersion::XCDRv2 == calculator.get_cdr_version() ?
                                eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2 :
                                eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR,
                                current_alignment)};


        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(0),
                data.frame_id(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(1),
                data.sequence_id(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(2),
                data.timestamp(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(3),
                data.robot_name(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(4),
                data.joints_name(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(5),
                data.joints_temperature(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(6),
                data.joints_position(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(7),
                data.joints_velocity(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(8),
                data.joints_acceleration(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(9),
                data.joints_torques(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(10),
                data.preassure1(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(11),
                data.preassure2(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(12),
                data.joints_torques_from_current(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(13),
                data.motors_current(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(14),
                data.feet_contact(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(15),
                data.feet_position(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(16),
                data.current_ref(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(17),
                data.position_ref(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(18),
                data.torque_ref(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(19),
                data.current_offset(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(20),
                data.torque_scale_factor(), current_alignment);

        calculated_size += calculator.calculate_member_serialized_size(eprosima::fastcdr::MemberId(21),
                data.chirp_freq(), current_alignment);


    calculated_size += calculator.end_calculate_type_serialized_size(previous_encoding, current_alignment);

    return calculated_size;
}

template<>
eProsima_user_DllExport void serialize(
        eprosima::fastcdr::Cdr& scdr,
        const EcatRobotStateMsg& data)
{
    eprosima::fastcdr::Cdr::state current_state(scdr);
    scdr.begin_serialize_type(current_state,
            eprosima::fastcdr::CdrVersion::XCDRv2 == scdr.get_cdr_version() ?
            eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2 :
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR);

    scdr
        << eprosima::fastcdr::MemberId(0) << data.frame_id()
        << eprosima::fastcdr::MemberId(1) << data.sequence_id()
        << eprosima::fastcdr::MemberId(2) << data.timestamp()
        << eprosima::fastcdr::MemberId(3) << data.robot_name()
        << eprosima::fastcdr::MemberId(4) << data.joints_name()
        << eprosima::fastcdr::MemberId(5) << data.joints_temperature()
        << eprosima::fastcdr::MemberId(6) << data.joints_position()
        << eprosima::fastcdr::MemberId(7) << data.joints_velocity()
        << eprosima::fastcdr::MemberId(8) << data.joints_acceleration()
        << eprosima::fastcdr::MemberId(9) << data.joints_torques()
        << eprosima::fastcdr::MemberId(10) << data.preassure1()
        << eprosima::fastcdr::MemberId(11) << data.preassure2()
        << eprosima::fastcdr::MemberId(12) << data.joints_torques_from_current()
        << eprosima::fastcdr::MemberId(13) << data.motors_current()
        << eprosima::fastcdr::MemberId(14) << data.feet_contact()
        << eprosima::fastcdr::MemberId(15) << data.feet_position()
        << eprosima::fastcdr::MemberId(16) << data.current_ref()
        << eprosima::fastcdr::MemberId(17) << data.position_ref()
        << eprosima::fastcdr::MemberId(18) << data.torque_ref()
        << eprosima::fastcdr::MemberId(19) << data.current_offset()
        << eprosima::fastcdr::MemberId(20) << data.torque_scale_factor()
        << eprosima::fastcdr::MemberId(21) << data.chirp_freq()
;
    scdr.end_serialize_type(current_state);
}

template<>
eProsima_user_DllExport void deserialize(
        eprosima::fastcdr::Cdr& cdr,
        EcatRobotStateMsg& data)
{
    cdr.deserialize_type(eprosima::fastcdr::CdrVersion::XCDRv2 == cdr.get_cdr_version() ?
            eprosima::fastcdr::EncodingAlgorithmFlag::DELIMIT_CDR2 :
            eprosima::fastcdr::EncodingAlgorithmFlag::PLAIN_CDR,
            [&data](eprosima::fastcdr::Cdr& dcdr, const eprosima::fastcdr::MemberId& mid) -> bool
            {
                bool ret_value = true;
                switch (mid.id)
                {
                                        case 0:
                                                dcdr >> data.frame_id();
                                            break;

                                        case 1:
                                                dcdr >> data.sequence_id();
                                            break;

                                        case 2:
                                                dcdr >> data.timestamp();
                                            break;

                                        case 3:
                                                dcdr >> data.robot_name();
                                            break;

                                        case 4:
                                                dcdr >> data.joints_name();
                                            break;

                                        case 5:
                                                dcdr >> data.joints_temperature();
                                            break;

                                        case 6:
                                                dcdr >> data.joints_position();
                                            break;

                                        case 7:
                                                dcdr >> data.joints_velocity();
                                            break;

                                        case 8:
                                                dcdr >> data.joints_acceleration();
                                            break;

                                        case 9:
                                                dcdr >> data.joints_torques();
                                            break;

                                        case 10:
                                                dcdr >> data.preassure1();
                                            break;

                                        case 11:
                                                dcdr >> data.preassure2();
                                            break;

                                        case 12:
                                                dcdr >> data.joints_torques_from_current();
                                            break;

                                        case 13:
                                                dcdr >> data.motors_current();
                                            break;

                                        case 14:
                                                dcdr >> data.feet_contact();
                                            break;

                                        case 15:
                                                dcdr >> data.feet_position();
                                            break;

                                        case 16:
                                                dcdr >> data.current_ref();
                                            break;

                                        case 17:
                                                dcdr >> data.position_ref();
                                            break;

                                        case 18:
                                                dcdr >> data.torque_ref();
                                            break;

                                        case 19:
                                                dcdr >> data.current_offset();
                                            break;

                                        case 20:
                                                dcdr >> data.torque_scale_factor();
                                            break;

                                        case 21:
                                                dcdr >> data.chirp_freq();
                                            break;

                    default:
                        ret_value = false;
                        break;
                }
                return ret_value;
            });
}

void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const EcatRobotStateMsg& data)
{

    static_cast<void>(scdr);
    static_cast<void>(data);
                        scdr << data.frame_id();

                        scdr << data.sequence_id();

                        scdr << data.timestamp();

                        scdr << data.robot_name();

                        scdr << data.joints_name();

                        scdr << data.joints_temperature();

                        scdr << data.joints_position();

                        scdr << data.joints_velocity();

                        scdr << data.joints_acceleration();

                        scdr << data.joints_torques();

                        scdr << data.preassure1();

                        scdr << data.preassure2();

                        scdr << data.joints_torques_from_current();

                        scdr << data.motors_current();

                        scdr << data.feet_contact();

                        scdr << data.feet_position();

                        scdr << data.current_ref();

                        scdr << data.position_ref();

                        scdr << data.torque_ref();

                        scdr << data.current_offset();

                        scdr << data.torque_scale_factor();

                        scdr << data.chirp_freq();

}



} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__ECAT_ROBOT_STATECDRAUX_IPP

