// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ecat_valve_refTypeObject.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "ecat_valve_ref.h"
#include "ecat_valve_refTypeObject.h"
#include <mutex>
#include <utility>
#include <sstream>
#include <fastrtps/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>
#include <fastrtps/types/TypeObjectFactory.h>
#include <fastrtps/types/TypeNamesGenerator.h>
#include <fastrtps/types/AnnotationParameterValue.h>
#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

using namespace eprosima::fastrtps::rtps;

void registerecat_valve_refTypes()
{
    static std::once_flag once_flag;
    std::call_once(once_flag, []()
            {
                TypeObjectFactory *factory = TypeObjectFactory::get_instance();
                factory->add_type_object("ECValveRefMsg", GetECValveRefMsgIdentifier(true),
                GetECValveRefMsgObject(true));
                factory->add_type_object("ECValveRefMsg", GetECValveRefMsgIdentifier(false),
                GetECValveRefMsgObject(false));

            });
}

const TypeIdentifier* GetECValveRefMsgIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("ECValveRefMsg", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetECValveRefMsgObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("ECValveRefMsg", complete);
}

const TypeObject* GetECValveRefMsgObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("ECValveRefMsg", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteECValveRefMsgObject();
    }
    //else
    return GetMinimalECValveRefMsgObject();
}

const TypeObject* GetMinimalECValveRefMsgObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("ECValveRefMsg", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_timestamp;
    mst_timestamp.common().member_id(memberId++);
    mst_timestamp.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_timestamp.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_timestamp.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_timestamp.common().member_flags().IS_OPTIONAL(false);
    mst_timestamp.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_timestamp.common().member_flags().IS_KEY(false);
    mst_timestamp.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_timestamp.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 timestamp_hash("timestamp");
    for(int i = 0; i < 4; ++i)
    {
        mst_timestamp.detail().name_hash()[i] = timestamp_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_timestamp);

    MinimalStructMember mst_kp_force;
    mst_kp_force.common().member_id(memberId++);
    mst_kp_force.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_kp_force.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_kp_force.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_kp_force.common().member_flags().IS_OPTIONAL(false);
    mst_kp_force.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_kp_force.common().member_flags().IS_KEY(false);
    mst_kp_force.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_kp_force.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 kp_force_hash("kp_force");
    for(int i = 0; i < 4; ++i)
    {
        mst_kp_force.detail().name_hash()[i] = kp_force_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_kp_force);

    MinimalStructMember mst_ki_force;
    mst_ki_force.common().member_id(memberId++);
    mst_ki_force.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_ki_force.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_ki_force.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_ki_force.common().member_flags().IS_OPTIONAL(false);
    mst_ki_force.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_ki_force.common().member_flags().IS_KEY(false);
    mst_ki_force.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_ki_force.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 ki_force_hash("ki_force");
    for(int i = 0; i < 4; ++i)
    {
        mst_ki_force.detail().name_hash()[i] = ki_force_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_ki_force);

    MinimalStructMember mst_kd_force;
    mst_kd_force.common().member_id(memberId++);
    mst_kd_force.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_kd_force.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_kd_force.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_kd_force.common().member_flags().IS_OPTIONAL(false);
    mst_kd_force.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_kd_force.common().member_flags().IS_KEY(false);
    mst_kd_force.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_kd_force.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 kd_force_hash("kd_force");
    for(int i = 0; i < 4; ++i)
    {
        mst_kd_force.detail().name_hash()[i] = kd_force_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_kd_force);

    MinimalStructMember mst_kp_position;
    mst_kp_position.common().member_id(memberId++);
    mst_kp_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_kp_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_kp_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_kp_position.common().member_flags().IS_OPTIONAL(false);
    mst_kp_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_kp_position.common().member_flags().IS_KEY(false);
    mst_kp_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_kp_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 kp_position_hash("kp_position");
    for(int i = 0; i < 4; ++i)
    {
        mst_kp_position.detail().name_hash()[i] = kp_position_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_kp_position);

    MinimalStructMember mst_ki_position;
    mst_ki_position.common().member_id(memberId++);
    mst_ki_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_ki_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_ki_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_ki_position.common().member_flags().IS_OPTIONAL(false);
    mst_ki_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_ki_position.common().member_flags().IS_KEY(false);
    mst_ki_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_ki_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 ki_position_hash("ki_position");
    for(int i = 0; i < 4; ++i)
    {
        mst_ki_position.detail().name_hash()[i] = ki_position_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_ki_position);

    MinimalStructMember mst_kd_position;
    mst_kd_position.common().member_id(memberId++);
    mst_kd_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_kd_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_kd_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_kd_position.common().member_flags().IS_OPTIONAL(false);
    mst_kd_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_kd_position.common().member_flags().IS_KEY(false);
    mst_kd_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_kd_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 kd_position_hash("kd_position");
    for(int i = 0; i < 4; ++i)
    {
        mst_kd_position.detail().name_hash()[i] = kd_position_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_kd_position);

    MinimalStructMember mst_current_ref;
    mst_current_ref.common().member_id(memberId++);
    mst_current_ref.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_current_ref.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_current_ref.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_current_ref.common().member_flags().IS_OPTIONAL(false);
    mst_current_ref.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_current_ref.common().member_flags().IS_KEY(false);
    mst_current_ref.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_current_ref.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 current_ref_hash("current_ref");
    for(int i = 0; i < 4; ++i)
    {
        mst_current_ref.detail().name_hash()[i] = current_ref_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_current_ref);

    MinimalStructMember mst_position_ref;
    mst_position_ref.common().member_id(memberId++);
    mst_position_ref.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_position_ref.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_position_ref.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_position_ref.common().member_flags().IS_OPTIONAL(false);
    mst_position_ref.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_position_ref.common().member_flags().IS_KEY(false);
    mst_position_ref.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_position_ref.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 position_ref_hash("position_ref");
    for(int i = 0; i < 4; ++i)
    {
        mst_position_ref.detail().name_hash()[i] = position_ref_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_position_ref);

    MinimalStructMember mst_torque_ref;
    mst_torque_ref.common().member_id(memberId++);
    mst_torque_ref.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_torque_ref.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_torque_ref.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_torque_ref.common().member_flags().IS_OPTIONAL(false);
    mst_torque_ref.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_torque_ref.common().member_flags().IS_KEY(false);
    mst_torque_ref.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_torque_ref.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 torque_ref_hash("torque_ref");
    for(int i = 0; i < 4; ++i)
    {
        mst_torque_ref.detail().name_hash()[i] = torque_ref_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_torque_ref);

    MinimalStructMember mst_current_offset;
    mst_current_offset.common().member_id(memberId++);
    mst_current_offset.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_current_offset.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_current_offset.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_current_offset.common().member_flags().IS_OPTIONAL(false);
    mst_current_offset.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_current_offset.common().member_flags().IS_KEY(false);
    mst_current_offset.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_current_offset.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    MD5 current_offset_hash("current_offset");
    for(int i = 0; i < 4; ++i)
    {
        mst_current_offset.detail().name_hash()[i] = current_offset_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_current_offset);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("ECValveRefMsg", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("ECValveRefMsg", false);
}

const TypeObject* GetCompleteECValveRefMsgObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("ECValveRefMsg", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_timestamp;
    cst_timestamp.common().member_id(memberId++);
    cst_timestamp.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_timestamp.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_timestamp.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_timestamp.common().member_flags().IS_OPTIONAL(false);
    cst_timestamp.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_timestamp.common().member_flags().IS_KEY(false);
    cst_timestamp.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_timestamp.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_timestamp.detail().name("timestamp");

    type_object->complete().struct_type().member_seq().emplace_back(cst_timestamp);

    CompleteStructMember cst_kp_force;
    cst_kp_force.common().member_id(memberId++);
    cst_kp_force.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_kp_force.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_kp_force.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_kp_force.common().member_flags().IS_OPTIONAL(false);
    cst_kp_force.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_kp_force.common().member_flags().IS_KEY(false);
    cst_kp_force.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_kp_force.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_kp_force.detail().name("kp_force");

    type_object->complete().struct_type().member_seq().emplace_back(cst_kp_force);

    CompleteStructMember cst_ki_force;
    cst_ki_force.common().member_id(memberId++);
    cst_ki_force.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_ki_force.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_ki_force.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_ki_force.common().member_flags().IS_OPTIONAL(false);
    cst_ki_force.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_ki_force.common().member_flags().IS_KEY(false);
    cst_ki_force.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_ki_force.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_ki_force.detail().name("ki_force");

    type_object->complete().struct_type().member_seq().emplace_back(cst_ki_force);

    CompleteStructMember cst_kd_force;
    cst_kd_force.common().member_id(memberId++);
    cst_kd_force.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_kd_force.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_kd_force.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_kd_force.common().member_flags().IS_OPTIONAL(false);
    cst_kd_force.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_kd_force.common().member_flags().IS_KEY(false);
    cst_kd_force.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_kd_force.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_kd_force.detail().name("kd_force");

    type_object->complete().struct_type().member_seq().emplace_back(cst_kd_force);

    CompleteStructMember cst_kp_position;
    cst_kp_position.common().member_id(memberId++);
    cst_kp_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_kp_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_kp_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_kp_position.common().member_flags().IS_OPTIONAL(false);
    cst_kp_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_kp_position.common().member_flags().IS_KEY(false);
    cst_kp_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_kp_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_kp_position.detail().name("kp_position");

    type_object->complete().struct_type().member_seq().emplace_back(cst_kp_position);

    CompleteStructMember cst_ki_position;
    cst_ki_position.common().member_id(memberId++);
    cst_ki_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_ki_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_ki_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_ki_position.common().member_flags().IS_OPTIONAL(false);
    cst_ki_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_ki_position.common().member_flags().IS_KEY(false);
    cst_ki_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_ki_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_ki_position.detail().name("ki_position");

    type_object->complete().struct_type().member_seq().emplace_back(cst_ki_position);

    CompleteStructMember cst_kd_position;
    cst_kd_position.common().member_id(memberId++);
    cst_kd_position.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_kd_position.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_kd_position.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_kd_position.common().member_flags().IS_OPTIONAL(false);
    cst_kd_position.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_kd_position.common().member_flags().IS_KEY(false);
    cst_kd_position.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_kd_position.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_kd_position.detail().name("kd_position");

    type_object->complete().struct_type().member_seq().emplace_back(cst_kd_position);

    CompleteStructMember cst_current_ref;
    cst_current_ref.common().member_id(memberId++);
    cst_current_ref.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_current_ref.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_current_ref.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_current_ref.common().member_flags().IS_OPTIONAL(false);
    cst_current_ref.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_current_ref.common().member_flags().IS_KEY(false);
    cst_current_ref.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_current_ref.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_current_ref.detail().name("current_ref");

    type_object->complete().struct_type().member_seq().emplace_back(cst_current_ref);

    CompleteStructMember cst_position_ref;
    cst_position_ref.common().member_id(memberId++);
    cst_position_ref.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_position_ref.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_position_ref.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_position_ref.common().member_flags().IS_OPTIONAL(false);
    cst_position_ref.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_position_ref.common().member_flags().IS_KEY(false);
    cst_position_ref.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_position_ref.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_position_ref.detail().name("position_ref");

    type_object->complete().struct_type().member_seq().emplace_back(cst_position_ref);

    CompleteStructMember cst_torque_ref;
    cst_torque_ref.common().member_id(memberId++);
    cst_torque_ref.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_torque_ref.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_torque_ref.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_torque_ref.common().member_flags().IS_OPTIONAL(false);
    cst_torque_ref.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_torque_ref.common().member_flags().IS_KEY(false);
    cst_torque_ref.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_torque_ref.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_torque_ref.detail().name("torque_ref");

    type_object->complete().struct_type().member_seq().emplace_back(cst_torque_ref);

    CompleteStructMember cst_current_offset;
    cst_current_offset.common().member_id(memberId++);
    cst_current_offset.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_current_offset.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_current_offset.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_current_offset.common().member_flags().IS_OPTIONAL(false);
    cst_current_offset.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_current_offset.common().member_flags().IS_KEY(false);
    cst_current_offset.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_current_offset.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("double", false));

    cst_current_offset.detail().name("current_offset");

    type_object->complete().struct_type().member_seq().emplace_back(cst_current_offset);


    // Header
    type_object->complete().struct_type().header().detail().type_name("ECValveRefMsg");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("ECValveRefMsg", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("ECValveRefMsg", true);
}
