// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ecat_robot_stateTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "ecat_robot_stateTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "ecat_robot_state.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_EcatRobotStateMsg_type_identifier(
        TypeIdentifierPair& type_ids_EcatRobotStateMsg)
{

    ReturnCode_t return_code_EcatRobotStateMsg {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EcatRobotStateMsg =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EcatRobotStateMsg", type_ids_EcatRobotStateMsg);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EcatRobotStateMsg)
    {
        StructTypeFlag struct_flags_EcatRobotStateMsg = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_EcatRobotStateMsg = "EcatRobotStateMsg";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EcatRobotStateMsg;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EcatRobotStateMsg;
        CompleteTypeDetail detail_EcatRobotStateMsg = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EcatRobotStateMsg, ann_custom_EcatRobotStateMsg, type_name_EcatRobotStateMsg.to_string());
        CompleteStructHeader header_EcatRobotStateMsg;
        header_EcatRobotStateMsg = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_EcatRobotStateMsg);
        CompleteStructMemberSeq member_seq_EcatRobotStateMsg;
        {
            TypeIdentifierPair type_ids_frame_id;
            ReturnCode_t return_code_frame_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_frame_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_frame_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_frame_id)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_frame_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_frame_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_frame_id = 0x00000000;
            bool common_frame_id_ec {false};
            CommonStructMember common_frame_id {TypeObjectUtils::build_common_struct_member(member_id_frame_id, member_flags_frame_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frame_id, common_frame_id_ec))};
            if (!common_frame_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure frame_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_frame_id = "frame_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_frame_id;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_frame_id = TypeObjectUtils::build_complete_member_detail(name_frame_id, member_ann_builtin_frame_id, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_frame_id = TypeObjectUtils::build_complete_struct_member(common_frame_id, detail_frame_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_frame_id);
        }
        {
            TypeIdentifierPair type_ids_sequence_id;
            ReturnCode_t return_code_sequence_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sequence_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_sequence_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sequence_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "sequence_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_sequence_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sequence_id = 0x00000001;
            bool common_sequence_id_ec {false};
            CommonStructMember common_sequence_id {TypeObjectUtils::build_common_struct_member(member_id_sequence_id, member_flags_sequence_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sequence_id, common_sequence_id_ec))};
            if (!common_sequence_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sequence_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sequence_id = "sequence_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sequence_id;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_sequence_id = TypeObjectUtils::build_complete_member_detail(name_sequence_id, member_ann_builtin_sequence_id, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_sequence_id = TypeObjectUtils::build_complete_struct_member(common_sequence_id, detail_sequence_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_sequence_id);
        }
        {
            TypeIdentifierPair type_ids_timestamp;
            ReturnCode_t return_code_timestamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_timestamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp = 0x00000002;
            bool common_timestamp_ec {false};
            CommonStructMember common_timestamp {TypeObjectUtils::build_common_struct_member(member_id_timestamp, member_flags_timestamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp, common_timestamp_ec))};
            if (!common_timestamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp = "timestamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_timestamp = TypeObjectUtils::build_complete_member_detail(name_timestamp, member_ann_builtin_timestamp, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_timestamp = TypeObjectUtils::build_complete_struct_member(common_timestamp, detail_timestamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_timestamp);
        }
        {
            TypeIdentifierPair type_ids_robot_name;
            ReturnCode_t return_code_robot_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_robot_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_robot_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_robot_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_robot_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_robot_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_robot_name = 0x00000003;
            bool common_robot_name_ec {false};
            CommonStructMember common_robot_name {TypeObjectUtils::build_common_struct_member(member_id_robot_name, member_flags_robot_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_robot_name, common_robot_name_ec))};
            if (!common_robot_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure robot_name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_robot_name = "robot_name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_robot_name;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_robot_name = TypeObjectUtils::build_complete_member_detail(name_robot_name, member_ann_builtin_robot_name, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_robot_name = TypeObjectUtils::build_complete_struct_member(common_robot_name, detail_robot_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_robot_name);
        }
        {
            TypeIdentifierPair type_ids_joints_name;
            ReturnCode_t return_code_joints_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_joints_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_anonymous_string_unbounded_12", type_ids_joints_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_name)
            {
                return_code_joints_name =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "anonymous_string_unbounded", type_ids_joints_name);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_name)
                {
                    {
                        SBound bound = 0;
                        StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                                TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                                "anonymous_string_unbounded", type_ids_joints_name))
                        {
                            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                                "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                        }
                    }
                }
                bool element_identifier_anonymous_array_anonymous_string_unbounded_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_anonymous_string_unbounded_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_name, element_identifier_anonymous_array_anonymous_string_unbounded_12_ec))};
                if (!element_identifier_anonymous_array_anonymous_string_unbounded_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_anonymous_string_unbounded_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_joints_name.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_anonymous_string_unbounded_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_anonymous_string_unbounded_12 = 0;
                PlainCollectionHeader header_anonymous_array_anonymous_string_unbounded_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_anonymous_string_unbounded_12, element_flags_anonymous_array_anonymous_string_unbounded_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_anonymous_string_unbounded_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_anonymous_string_unbounded_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_anonymous_string_unbounded_12", type_ids_joints_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_anonymous_string_unbounded_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_joints_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_joints_name = 0x00000004;
            bool common_joints_name_ec {false};
            CommonStructMember common_joints_name {TypeObjectUtils::build_common_struct_member(member_id_joints_name, member_flags_joints_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_name, common_joints_name_ec))};
            if (!common_joints_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure joints_name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_joints_name = "joints_name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_joints_name;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_joints_name = TypeObjectUtils::build_complete_member_detail(name_joints_name, member_ann_builtin_joints_name, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_joints_name = TypeObjectUtils::build_complete_struct_member(common_joints_name, detail_joints_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_joints_name);
        }
        {
            TypeIdentifierPair type_ids_joints_temperature;
            ReturnCode_t return_code_joints_temperature {eprosima::fastdds::dds::RETCODE_OK};
            return_code_joints_temperature =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_joints_temperature);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_temperature)
            {
                return_code_joints_temperature =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_joints_temperature);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_temperature)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_temperature, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_joints_temperature.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_joints_temperature))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_joints_temperature = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_joints_temperature = 0x00000005;
            bool common_joints_temperature_ec {false};
            CommonStructMember common_joints_temperature {TypeObjectUtils::build_common_struct_member(member_id_joints_temperature, member_flags_joints_temperature, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_temperature, common_joints_temperature_ec))};
            if (!common_joints_temperature_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure joints_temperature member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_joints_temperature = "joints_temperature";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_joints_temperature;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_joints_temperature = TypeObjectUtils::build_complete_member_detail(name_joints_temperature, member_ann_builtin_joints_temperature, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_joints_temperature = TypeObjectUtils::build_complete_struct_member(common_joints_temperature, detail_joints_temperature);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_joints_temperature);
        }
        {
            TypeIdentifierPair type_ids_joints_position;
            ReturnCode_t return_code_joints_position {eprosima::fastdds::dds::RETCODE_OK};
            return_code_joints_position =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_joints_position);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_position)
            {
                return_code_joints_position =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_joints_position);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_position)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_position, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_joints_position.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_joints_position))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_joints_position = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_joints_position = 0x00000006;
            bool common_joints_position_ec {false};
            CommonStructMember common_joints_position {TypeObjectUtils::build_common_struct_member(member_id_joints_position, member_flags_joints_position, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_position, common_joints_position_ec))};
            if (!common_joints_position_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure joints_position member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_joints_position = "joints_position";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_joints_position;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_joints_position = TypeObjectUtils::build_complete_member_detail(name_joints_position, member_ann_builtin_joints_position, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_joints_position = TypeObjectUtils::build_complete_struct_member(common_joints_position, detail_joints_position);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_joints_position);
        }
        {
            TypeIdentifierPair type_ids_joints_velocity;
            ReturnCode_t return_code_joints_velocity {eprosima::fastdds::dds::RETCODE_OK};
            return_code_joints_velocity =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_joints_velocity);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_velocity)
            {
                return_code_joints_velocity =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_joints_velocity);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_velocity)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_velocity, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_joints_velocity.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_joints_velocity))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_joints_velocity = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_joints_velocity = 0x00000007;
            bool common_joints_velocity_ec {false};
            CommonStructMember common_joints_velocity {TypeObjectUtils::build_common_struct_member(member_id_joints_velocity, member_flags_joints_velocity, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_velocity, common_joints_velocity_ec))};
            if (!common_joints_velocity_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure joints_velocity member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_joints_velocity = "joints_velocity";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_joints_velocity;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_joints_velocity = TypeObjectUtils::build_complete_member_detail(name_joints_velocity, member_ann_builtin_joints_velocity, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_joints_velocity = TypeObjectUtils::build_complete_struct_member(common_joints_velocity, detail_joints_velocity);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_joints_velocity);
        }
        {
            TypeIdentifierPair type_ids_joints_acceleration;
            ReturnCode_t return_code_joints_acceleration {eprosima::fastdds::dds::RETCODE_OK};
            return_code_joints_acceleration =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_joints_acceleration);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_acceleration)
            {
                return_code_joints_acceleration =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_joints_acceleration);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_acceleration)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_acceleration, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_joints_acceleration.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_joints_acceleration))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_joints_acceleration = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_joints_acceleration = 0x00000008;
            bool common_joints_acceleration_ec {false};
            CommonStructMember common_joints_acceleration {TypeObjectUtils::build_common_struct_member(member_id_joints_acceleration, member_flags_joints_acceleration, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_acceleration, common_joints_acceleration_ec))};
            if (!common_joints_acceleration_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure joints_acceleration member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_joints_acceleration = "joints_acceleration";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_joints_acceleration;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_joints_acceleration = TypeObjectUtils::build_complete_member_detail(name_joints_acceleration, member_ann_builtin_joints_acceleration, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_joints_acceleration = TypeObjectUtils::build_complete_struct_member(common_joints_acceleration, detail_joints_acceleration);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_joints_acceleration);
        }
        {
            TypeIdentifierPair type_ids_joints_torques;
            ReturnCode_t return_code_joints_torques {eprosima::fastdds::dds::RETCODE_OK};
            return_code_joints_torques =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_joints_torques);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_torques)
            {
                return_code_joints_torques =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_joints_torques);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_torques)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_torques, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_joints_torques.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_joints_torques))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_joints_torques = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_joints_torques = 0x00000009;
            bool common_joints_torques_ec {false};
            CommonStructMember common_joints_torques {TypeObjectUtils::build_common_struct_member(member_id_joints_torques, member_flags_joints_torques, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_torques, common_joints_torques_ec))};
            if (!common_joints_torques_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure joints_torques member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_joints_torques = "joints_torques";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_joints_torques;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_joints_torques = TypeObjectUtils::build_complete_member_detail(name_joints_torques, member_ann_builtin_joints_torques, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_joints_torques = TypeObjectUtils::build_complete_struct_member(common_joints_torques, detail_joints_torques);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_joints_torques);
        }
        {
            TypeIdentifierPair type_ids_preassure1;
            ReturnCode_t return_code_preassure1 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_preassure1 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_preassure1);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_preassure1)
            {
                return_code_preassure1 =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_preassure1);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_preassure1)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_preassure1, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_preassure1.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_preassure1))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_preassure1 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_preassure1 = 0x0000000a;
            bool common_preassure1_ec {false};
            CommonStructMember common_preassure1 {TypeObjectUtils::build_common_struct_member(member_id_preassure1, member_flags_preassure1, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_preassure1, common_preassure1_ec))};
            if (!common_preassure1_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure preassure1 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_preassure1 = "preassure1";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_preassure1;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_preassure1 = TypeObjectUtils::build_complete_member_detail(name_preassure1, member_ann_builtin_preassure1, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_preassure1 = TypeObjectUtils::build_complete_struct_member(common_preassure1, detail_preassure1);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_preassure1);
        }
        {
            TypeIdentifierPair type_ids_preassure2;
            ReturnCode_t return_code_preassure2 {eprosima::fastdds::dds::RETCODE_OK};
            return_code_preassure2 =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_preassure2);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_preassure2)
            {
                return_code_preassure2 =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_preassure2);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_preassure2)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_preassure2, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_preassure2.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_preassure2))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_preassure2 = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_preassure2 = 0x0000000b;
            bool common_preassure2_ec {false};
            CommonStructMember common_preassure2 {TypeObjectUtils::build_common_struct_member(member_id_preassure2, member_flags_preassure2, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_preassure2, common_preassure2_ec))};
            if (!common_preassure2_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure preassure2 member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_preassure2 = "preassure2";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_preassure2;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_preassure2 = TypeObjectUtils::build_complete_member_detail(name_preassure2, member_ann_builtin_preassure2, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_preassure2 = TypeObjectUtils::build_complete_struct_member(common_preassure2, detail_preassure2);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_preassure2);
        }
        {
            TypeIdentifierPair type_ids_joints_torques_from_current;
            ReturnCode_t return_code_joints_torques_from_current {eprosima::fastdds::dds::RETCODE_OK};
            return_code_joints_torques_from_current =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_joints_torques_from_current);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_torques_from_current)
            {
                return_code_joints_torques_from_current =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_joints_torques_from_current);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_joints_torques_from_current)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_torques_from_current, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_joints_torques_from_current.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_joints_torques_from_current))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_joints_torques_from_current = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_joints_torques_from_current = 0x0000000c;
            bool common_joints_torques_from_current_ec {false};
            CommonStructMember common_joints_torques_from_current {TypeObjectUtils::build_common_struct_member(member_id_joints_torques_from_current, member_flags_joints_torques_from_current, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_joints_torques_from_current, common_joints_torques_from_current_ec))};
            if (!common_joints_torques_from_current_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure joints_torques_from_current member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_joints_torques_from_current = "joints_torques_from_current";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_joints_torques_from_current;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_joints_torques_from_current = TypeObjectUtils::build_complete_member_detail(name_joints_torques_from_current, member_ann_builtin_joints_torques_from_current, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_joints_torques_from_current = TypeObjectUtils::build_complete_struct_member(common_joints_torques_from_current, detail_joints_torques_from_current);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_joints_torques_from_current);
        }
        {
            TypeIdentifierPair type_ids_motors_current;
            ReturnCode_t return_code_motors_current {eprosima::fastdds::dds::RETCODE_OK};
            return_code_motors_current =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_motors_current);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_motors_current)
            {
                return_code_motors_current =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_motors_current);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_motors_current)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_motors_current, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_motors_current.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_motors_current))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_motors_current = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_motors_current = 0x0000000d;
            bool common_motors_current_ec {false};
            CommonStructMember common_motors_current {TypeObjectUtils::build_common_struct_member(member_id_motors_current, member_flags_motors_current, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_motors_current, common_motors_current_ec))};
            if (!common_motors_current_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure motors_current member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_motors_current = "motors_current";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_motors_current;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_motors_current = TypeObjectUtils::build_complete_member_detail(name_motors_current, member_ann_builtin_motors_current, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_motors_current = TypeObjectUtils::build_complete_struct_member(common_motors_current, detail_motors_current);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_motors_current);
        }
        {
            TypeIdentifierPair type_ids_feet_contact;
            ReturnCode_t return_code_feet_contact {eprosima::fastdds::dds::RETCODE_OK};
            return_code_feet_contact =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_4", type_ids_feet_contact);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_feet_contact)
            {
                return_code_feet_contact =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_feet_contact);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_feet_contact)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_4_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_4 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_feet_contact, element_identifier_anonymous_array_double_4_ec))};
                if (!element_identifier_anonymous_array_double_4_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_4 = EK_COMPLETE;
                if (TK_NONE == type_ids_feet_contact.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_4 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_4 = 0;
                PlainCollectionHeader header_anonymous_array_double_4 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_4, element_flags_anonymous_array_double_4);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(4));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_4, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_4));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_4", type_ids_feet_contact))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_4 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_feet_contact = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_feet_contact = 0x0000000e;
            bool common_feet_contact_ec {false};
            CommonStructMember common_feet_contact {TypeObjectUtils::build_common_struct_member(member_id_feet_contact, member_flags_feet_contact, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_feet_contact, common_feet_contact_ec))};
            if (!common_feet_contact_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure feet_contact member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_feet_contact = "feet_contact";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_feet_contact;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_feet_contact = TypeObjectUtils::build_complete_member_detail(name_feet_contact, member_ann_builtin_feet_contact, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_feet_contact = TypeObjectUtils::build_complete_struct_member(common_feet_contact, detail_feet_contact);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_feet_contact);
        }
        {
            TypeIdentifierPair type_ids_feet_position;
            ReturnCode_t return_code_feet_position {eprosima::fastdds::dds::RETCODE_OK};
            return_code_feet_position =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_feet_position);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_feet_position)
            {
                return_code_feet_position =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_feet_position);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_feet_position)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_feet_position, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_feet_position.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_feet_position))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_feet_position = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_feet_position = 0x0000000f;
            bool common_feet_position_ec {false};
            CommonStructMember common_feet_position {TypeObjectUtils::build_common_struct_member(member_id_feet_position, member_flags_feet_position, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_feet_position, common_feet_position_ec))};
            if (!common_feet_position_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure feet_position member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_feet_position = "feet_position";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_feet_position;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_feet_position = TypeObjectUtils::build_complete_member_detail(name_feet_position, member_ann_builtin_feet_position, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_feet_position = TypeObjectUtils::build_complete_struct_member(common_feet_position, detail_feet_position);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_feet_position);
        }
        {
            TypeIdentifierPair type_ids_current_ref;
            ReturnCode_t return_code_current_ref {eprosima::fastdds::dds::RETCODE_OK};
            return_code_current_ref =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_current_ref);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_current_ref)
            {
                return_code_current_ref =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_current_ref);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_current_ref)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current_ref, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_current_ref.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_current_ref))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_current_ref = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_current_ref = 0x00000010;
            bool common_current_ref_ec {false};
            CommonStructMember common_current_ref {TypeObjectUtils::build_common_struct_member(member_id_current_ref, member_flags_current_ref, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current_ref, common_current_ref_ec))};
            if (!common_current_ref_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure current_ref member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_current_ref = "current_ref";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_current_ref;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_current_ref = TypeObjectUtils::build_complete_member_detail(name_current_ref, member_ann_builtin_current_ref, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_current_ref = TypeObjectUtils::build_complete_struct_member(common_current_ref, detail_current_ref);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_current_ref);
        }
        {
            TypeIdentifierPair type_ids_position_ref;
            ReturnCode_t return_code_position_ref {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position_ref =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_position_ref);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position_ref)
            {
                return_code_position_ref =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_position_ref);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_position_ref)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position_ref, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_position_ref.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_position_ref))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_position_ref = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position_ref = 0x00000011;
            bool common_position_ref_ec {false};
            CommonStructMember common_position_ref {TypeObjectUtils::build_common_struct_member(member_id_position_ref, member_flags_position_ref, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position_ref, common_position_ref_ec))};
            if (!common_position_ref_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position_ref member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position_ref = "position_ref";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position_ref;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_position_ref = TypeObjectUtils::build_complete_member_detail(name_position_ref, member_ann_builtin_position_ref, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_position_ref = TypeObjectUtils::build_complete_struct_member(common_position_ref, detail_position_ref);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_position_ref);
        }
        {
            TypeIdentifierPair type_ids_torque_ref;
            ReturnCode_t return_code_torque_ref {eprosima::fastdds::dds::RETCODE_OK};
            return_code_torque_ref =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_torque_ref);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque_ref)
            {
                return_code_torque_ref =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_torque_ref);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque_ref)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque_ref, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_torque_ref.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_torque_ref))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_torque_ref = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_torque_ref = 0x00000012;
            bool common_torque_ref_ec {false};
            CommonStructMember common_torque_ref {TypeObjectUtils::build_common_struct_member(member_id_torque_ref, member_flags_torque_ref, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque_ref, common_torque_ref_ec))};
            if (!common_torque_ref_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure torque_ref member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_torque_ref = "torque_ref";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_torque_ref;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_torque_ref = TypeObjectUtils::build_complete_member_detail(name_torque_ref, member_ann_builtin_torque_ref, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_torque_ref = TypeObjectUtils::build_complete_struct_member(common_torque_ref, detail_torque_ref);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_torque_ref);
        }
        {
            TypeIdentifierPair type_ids_current_offset;
            ReturnCode_t return_code_current_offset {eprosima::fastdds::dds::RETCODE_OK};
            return_code_current_offset =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_current_offset);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_current_offset)
            {
                return_code_current_offset =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_current_offset);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_current_offset)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current_offset, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_current_offset.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_current_offset))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_current_offset = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_current_offset = 0x00000013;
            bool common_current_offset_ec {false};
            CommonStructMember common_current_offset {TypeObjectUtils::build_common_struct_member(member_id_current_offset, member_flags_current_offset, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current_offset, common_current_offset_ec))};
            if (!common_current_offset_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure current_offset member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_current_offset = "current_offset";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_current_offset;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_current_offset = TypeObjectUtils::build_complete_member_detail(name_current_offset, member_ann_builtin_current_offset, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_current_offset = TypeObjectUtils::build_complete_struct_member(common_current_offset, detail_current_offset);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_current_offset);
        }
        {
            TypeIdentifierPair type_ids_torque_scale_factor;
            ReturnCode_t return_code_torque_scale_factor {eprosima::fastdds::dds::RETCODE_OK};
            return_code_torque_scale_factor =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_torque_scale_factor);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque_scale_factor)
            {
                return_code_torque_scale_factor =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_torque_scale_factor);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque_scale_factor)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque_scale_factor, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_torque_scale_factor.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_torque_scale_factor))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_torque_scale_factor = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_torque_scale_factor = 0x00000014;
            bool common_torque_scale_factor_ec {false};
            CommonStructMember common_torque_scale_factor {TypeObjectUtils::build_common_struct_member(member_id_torque_scale_factor, member_flags_torque_scale_factor, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque_scale_factor, common_torque_scale_factor_ec))};
            if (!common_torque_scale_factor_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure torque_scale_factor member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_torque_scale_factor = "torque_scale_factor";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_torque_scale_factor;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_torque_scale_factor = TypeObjectUtils::build_complete_member_detail(name_torque_scale_factor, member_ann_builtin_torque_scale_factor, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_torque_scale_factor = TypeObjectUtils::build_complete_struct_member(common_torque_scale_factor, detail_torque_scale_factor);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_torque_scale_factor);
        }
        {
            TypeIdentifierPair type_ids_chirp_freq;
            ReturnCode_t return_code_chirp_freq {eprosima::fastdds::dds::RETCODE_OK};
            return_code_chirp_freq =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_double_12", type_ids_chirp_freq);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_chirp_freq)
            {
                return_code_chirp_freq =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_chirp_freq);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_chirp_freq)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_double_12_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_double_12 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_chirp_freq, element_identifier_anonymous_array_double_12_ec))};
                if (!element_identifier_anonymous_array_double_12_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_double_12 = EK_COMPLETE;
                if (TK_NONE == type_ids_chirp_freq.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_double_12 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_double_12 = 0;
                PlainCollectionHeader header_anonymous_array_double_12 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_double_12, element_flags_anonymous_array_double_12);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(12));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_double_12, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_double_12));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_double_12", type_ids_chirp_freq))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_double_12 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_chirp_freq = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_chirp_freq = 0x00000015;
            bool common_chirp_freq_ec {false};
            CommonStructMember common_chirp_freq {TypeObjectUtils::build_common_struct_member(member_id_chirp_freq, member_flags_chirp_freq, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_chirp_freq, common_chirp_freq_ec))};
            if (!common_chirp_freq_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure chirp_freq member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_chirp_freq = "chirp_freq";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_chirp_freq;
            ann_custom_EcatRobotStateMsg.reset();
            CompleteMemberDetail detail_chirp_freq = TypeObjectUtils::build_complete_member_detail(name_chirp_freq, member_ann_builtin_chirp_freq, ann_custom_EcatRobotStateMsg);
            CompleteStructMember member_chirp_freq = TypeObjectUtils::build_complete_struct_member(common_chirp_freq, detail_chirp_freq);
            TypeObjectUtils::add_complete_struct_member(member_seq_EcatRobotStateMsg, member_chirp_freq);
        }
        CompleteStructType struct_type_EcatRobotStateMsg = TypeObjectUtils::build_complete_struct_type(struct_flags_EcatRobotStateMsg, header_EcatRobotStateMsg, member_seq_EcatRobotStateMsg);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_EcatRobotStateMsg, type_name_EcatRobotStateMsg.to_string(), type_ids_EcatRobotStateMsg))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "EcatRobotStateMsg already registered in TypeObjectRegistry for a different type.");
        }
    }
}

