struct EcatRobotStateMsg
{
	// Robot State
	// Header
	string frame_id;
	unsigned long sequence_id;
	double timestamp;

	string robot_name;

	string joints_name[12];
	double joints_temperature[12];
	double joints_position[12];
	double joints_velocity[12];
	double joints_acceleration[12];
	double joints_torques[12];
	double preassure1[12];
	double preassure2[12];
	double joints_torques_from_current[12];
	double motors_current[12];

	double feet_contact[4];
	double feet_position[12];


	// Saving desired reference for debugging
	double current_ref[12];
	double position_ref[12];
	double torque_ref[12];
	double current_offset[12];
	
	// scaling factor for the torque estimated by the current
	double torque_scale_factor[12];

	double chirp_freq[12];
};