// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ecat_robot_ref.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__ECAT_ROBOT_REF_HPP
#define FAST_DDS_GENERATED__ECAT_ROBOT_REF_HPP

#include <array>
#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ECAT_ROBOT_REF_SOURCE)
#define ECAT_ROBOT_REF_DllAPI __declspec( dllexport )
#else
#define ECAT_ROBOT_REF_DllAPI __declspec( dllimport )
#endif // ECAT_ROBOT_REF_SOURCE
#else
#define ECAT_ROBOT_REF_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ECAT_ROBOT_REF_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure EcatRobotRefMsg defined by the user in the IDL file.
 * @ingroup ecat_robot_ref
 */
class EcatRobotRefMsg
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport EcatRobotRefMsg()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~EcatRobotRefMsg()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object EcatRobotRefMsg that will be copied.
     */
    eProsima_user_DllExport EcatRobotRefMsg(
            const EcatRobotRefMsg& x)
    {
                    m_frame_id = x.m_frame_id;

                    m_sequence_id = x.m_sequence_id;

                    m_timestamp = x.m_timestamp;

                    m_kp_torque = x.m_kp_torque;

                    m_ki_torque = x.m_ki_torque;

                    m_kd_torque = x.m_kd_torque;

                    m_kp_position = x.m_kp_position;

                    m_ki_position = x.m_ki_position;

                    m_kd_position = x.m_kd_position;

                    m_current_ref = x.m_current_ref;

                    m_position_ref = x.m_position_ref;

                    m_torque_ref = x.m_torque_ref;

                    m_current_offset = x.m_current_offset;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object EcatRobotRefMsg that will be copied.
     */
    eProsima_user_DllExport EcatRobotRefMsg(
            EcatRobotRefMsg&& x) noexcept
    {
        m_frame_id = std::move(x.m_frame_id);
        m_sequence_id = x.m_sequence_id;
        m_timestamp = x.m_timestamp;
        m_kp_torque = std::move(x.m_kp_torque);
        m_ki_torque = std::move(x.m_ki_torque);
        m_kd_torque = std::move(x.m_kd_torque);
        m_kp_position = std::move(x.m_kp_position);
        m_ki_position = std::move(x.m_ki_position);
        m_kd_position = std::move(x.m_kd_position);
        m_current_ref = std::move(x.m_current_ref);
        m_position_ref = std::move(x.m_position_ref);
        m_torque_ref = std::move(x.m_torque_ref);
        m_current_offset = std::move(x.m_current_offset);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object EcatRobotRefMsg that will be copied.
     */
    eProsima_user_DllExport EcatRobotRefMsg& operator =(
            const EcatRobotRefMsg& x)
    {

                    m_frame_id = x.m_frame_id;

                    m_sequence_id = x.m_sequence_id;

                    m_timestamp = x.m_timestamp;

                    m_kp_torque = x.m_kp_torque;

                    m_ki_torque = x.m_ki_torque;

                    m_kd_torque = x.m_kd_torque;

                    m_kp_position = x.m_kp_position;

                    m_ki_position = x.m_ki_position;

                    m_kd_position = x.m_kd_position;

                    m_current_ref = x.m_current_ref;

                    m_position_ref = x.m_position_ref;

                    m_torque_ref = x.m_torque_ref;

                    m_current_offset = x.m_current_offset;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object EcatRobotRefMsg that will be copied.
     */
    eProsima_user_DllExport EcatRobotRefMsg& operator =(
            EcatRobotRefMsg&& x) noexcept
    {

        m_frame_id = std::move(x.m_frame_id);
        m_sequence_id = x.m_sequence_id;
        m_timestamp = x.m_timestamp;
        m_kp_torque = std::move(x.m_kp_torque);
        m_ki_torque = std::move(x.m_ki_torque);
        m_kd_torque = std::move(x.m_kd_torque);
        m_kp_position = std::move(x.m_kp_position);
        m_ki_position = std::move(x.m_ki_position);
        m_kd_position = std::move(x.m_kd_position);
        m_current_ref = std::move(x.m_current_ref);
        m_position_ref = std::move(x.m_position_ref);
        m_torque_ref = std::move(x.m_torque_ref);
        m_current_offset = std::move(x.m_current_offset);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x EcatRobotRefMsg object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const EcatRobotRefMsg& x) const
    {
        return (m_frame_id == x.m_frame_id &&
           m_sequence_id == x.m_sequence_id &&
           m_timestamp == x.m_timestamp &&
           m_kp_torque == x.m_kp_torque &&
           m_ki_torque == x.m_ki_torque &&
           m_kd_torque == x.m_kd_torque &&
           m_kp_position == x.m_kp_position &&
           m_ki_position == x.m_ki_position &&
           m_kd_position == x.m_kd_position &&
           m_current_ref == x.m_current_ref &&
           m_position_ref == x.m_position_ref &&
           m_torque_ref == x.m_torque_ref &&
           m_current_offset == x.m_current_offset);
    }

    /*!
     * @brief Comparison operator.
     * @param x EcatRobotRefMsg object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const EcatRobotRefMsg& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const std::string& _frame_id)
    {
        m_frame_id = _frame_id;
    }

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            std::string&& _frame_id)
    {
        m_frame_id = std::move(_frame_id);
    }

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const std::string& frame_id() const
    {
        return m_frame_id;
    }

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport std::string& frame_id()
    {
        return m_frame_id;
    }


    /*!
     * @brief This function sets a value in member sequence_id
     * @param _sequence_id New value for member sequence_id
     */
    eProsima_user_DllExport void sequence_id(
            uint32_t _sequence_id)
    {
        m_sequence_id = _sequence_id;
    }

    /*!
     * @brief This function returns the value of member sequence_id
     * @return Value of member sequence_id
     */
    eProsima_user_DllExport uint32_t sequence_id() const
    {
        return m_sequence_id;
    }

    /*!
     * @brief This function returns a reference to member sequence_id
     * @return Reference to member sequence_id
     */
    eProsima_user_DllExport uint32_t& sequence_id()
    {
        return m_sequence_id;
    }


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            double _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport double timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport double& timestamp()
    {
        return m_timestamp;
    }


    /*!
     * @brief This function copies the value in member kp_torque
     * @param _kp_torque New value to be copied in member kp_torque
     */
    eProsima_user_DllExport void kp_torque(
            const std::array<double, 12>& _kp_torque)
    {
        m_kp_torque = _kp_torque;
    }

    /*!
     * @brief This function moves the value in member kp_torque
     * @param _kp_torque New value to be moved in member kp_torque
     */
    eProsima_user_DllExport void kp_torque(
            std::array<double, 12>&& _kp_torque)
    {
        m_kp_torque = std::move(_kp_torque);
    }

    /*!
     * @brief This function returns a constant reference to member kp_torque
     * @return Constant reference to member kp_torque
     */
    eProsima_user_DllExport const std::array<double, 12>& kp_torque() const
    {
        return m_kp_torque;
    }

    /*!
     * @brief This function returns a reference to member kp_torque
     * @return Reference to member kp_torque
     */
    eProsima_user_DllExport std::array<double, 12>& kp_torque()
    {
        return m_kp_torque;
    }


    /*!
     * @brief This function copies the value in member ki_torque
     * @param _ki_torque New value to be copied in member ki_torque
     */
    eProsima_user_DllExport void ki_torque(
            const std::array<double, 12>& _ki_torque)
    {
        m_ki_torque = _ki_torque;
    }

    /*!
     * @brief This function moves the value in member ki_torque
     * @param _ki_torque New value to be moved in member ki_torque
     */
    eProsima_user_DllExport void ki_torque(
            std::array<double, 12>&& _ki_torque)
    {
        m_ki_torque = std::move(_ki_torque);
    }

    /*!
     * @brief This function returns a constant reference to member ki_torque
     * @return Constant reference to member ki_torque
     */
    eProsima_user_DllExport const std::array<double, 12>& ki_torque() const
    {
        return m_ki_torque;
    }

    /*!
     * @brief This function returns a reference to member ki_torque
     * @return Reference to member ki_torque
     */
    eProsima_user_DllExport std::array<double, 12>& ki_torque()
    {
        return m_ki_torque;
    }


    /*!
     * @brief This function copies the value in member kd_torque
     * @param _kd_torque New value to be copied in member kd_torque
     */
    eProsima_user_DllExport void kd_torque(
            const std::array<double, 12>& _kd_torque)
    {
        m_kd_torque = _kd_torque;
    }

    /*!
     * @brief This function moves the value in member kd_torque
     * @param _kd_torque New value to be moved in member kd_torque
     */
    eProsima_user_DllExport void kd_torque(
            std::array<double, 12>&& _kd_torque)
    {
        m_kd_torque = std::move(_kd_torque);
    }

    /*!
     * @brief This function returns a constant reference to member kd_torque
     * @return Constant reference to member kd_torque
     */
    eProsima_user_DllExport const std::array<double, 12>& kd_torque() const
    {
        return m_kd_torque;
    }

    /*!
     * @brief This function returns a reference to member kd_torque
     * @return Reference to member kd_torque
     */
    eProsima_user_DllExport std::array<double, 12>& kd_torque()
    {
        return m_kd_torque;
    }


    /*!
     * @brief This function copies the value in member kp_position
     * @param _kp_position New value to be copied in member kp_position
     */
    eProsima_user_DllExport void kp_position(
            const std::array<double, 12>& _kp_position)
    {
        m_kp_position = _kp_position;
    }

    /*!
     * @brief This function moves the value in member kp_position
     * @param _kp_position New value to be moved in member kp_position
     */
    eProsima_user_DllExport void kp_position(
            std::array<double, 12>&& _kp_position)
    {
        m_kp_position = std::move(_kp_position);
    }

    /*!
     * @brief This function returns a constant reference to member kp_position
     * @return Constant reference to member kp_position
     */
    eProsima_user_DllExport const std::array<double, 12>& kp_position() const
    {
        return m_kp_position;
    }

    /*!
     * @brief This function returns a reference to member kp_position
     * @return Reference to member kp_position
     */
    eProsima_user_DllExport std::array<double, 12>& kp_position()
    {
        return m_kp_position;
    }


    /*!
     * @brief This function copies the value in member ki_position
     * @param _ki_position New value to be copied in member ki_position
     */
    eProsima_user_DllExport void ki_position(
            const std::array<double, 12>& _ki_position)
    {
        m_ki_position = _ki_position;
    }

    /*!
     * @brief This function moves the value in member ki_position
     * @param _ki_position New value to be moved in member ki_position
     */
    eProsima_user_DllExport void ki_position(
            std::array<double, 12>&& _ki_position)
    {
        m_ki_position = std::move(_ki_position);
    }

    /*!
     * @brief This function returns a constant reference to member ki_position
     * @return Constant reference to member ki_position
     */
    eProsima_user_DllExport const std::array<double, 12>& ki_position() const
    {
        return m_ki_position;
    }

    /*!
     * @brief This function returns a reference to member ki_position
     * @return Reference to member ki_position
     */
    eProsima_user_DllExport std::array<double, 12>& ki_position()
    {
        return m_ki_position;
    }


    /*!
     * @brief This function copies the value in member kd_position
     * @param _kd_position New value to be copied in member kd_position
     */
    eProsima_user_DllExport void kd_position(
            const std::array<double, 12>& _kd_position)
    {
        m_kd_position = _kd_position;
    }

    /*!
     * @brief This function moves the value in member kd_position
     * @param _kd_position New value to be moved in member kd_position
     */
    eProsima_user_DllExport void kd_position(
            std::array<double, 12>&& _kd_position)
    {
        m_kd_position = std::move(_kd_position);
    }

    /*!
     * @brief This function returns a constant reference to member kd_position
     * @return Constant reference to member kd_position
     */
    eProsima_user_DllExport const std::array<double, 12>& kd_position() const
    {
        return m_kd_position;
    }

    /*!
     * @brief This function returns a reference to member kd_position
     * @return Reference to member kd_position
     */
    eProsima_user_DllExport std::array<double, 12>& kd_position()
    {
        return m_kd_position;
    }


    /*!
     * @brief This function copies the value in member current_ref
     * @param _current_ref New value to be copied in member current_ref
     */
    eProsima_user_DllExport void current_ref(
            const std::array<double, 12>& _current_ref)
    {
        m_current_ref = _current_ref;
    }

    /*!
     * @brief This function moves the value in member current_ref
     * @param _current_ref New value to be moved in member current_ref
     */
    eProsima_user_DllExport void current_ref(
            std::array<double, 12>&& _current_ref)
    {
        m_current_ref = std::move(_current_ref);
    }

    /*!
     * @brief This function returns a constant reference to member current_ref
     * @return Constant reference to member current_ref
     */
    eProsima_user_DllExport const std::array<double, 12>& current_ref() const
    {
        return m_current_ref;
    }

    /*!
     * @brief This function returns a reference to member current_ref
     * @return Reference to member current_ref
     */
    eProsima_user_DllExport std::array<double, 12>& current_ref()
    {
        return m_current_ref;
    }


    /*!
     * @brief This function copies the value in member position_ref
     * @param _position_ref New value to be copied in member position_ref
     */
    eProsima_user_DllExport void position_ref(
            const std::array<double, 12>& _position_ref)
    {
        m_position_ref = _position_ref;
    }

    /*!
     * @brief This function moves the value in member position_ref
     * @param _position_ref New value to be moved in member position_ref
     */
    eProsima_user_DllExport void position_ref(
            std::array<double, 12>&& _position_ref)
    {
        m_position_ref = std::move(_position_ref);
    }

    /*!
     * @brief This function returns a constant reference to member position_ref
     * @return Constant reference to member position_ref
     */
    eProsima_user_DllExport const std::array<double, 12>& position_ref() const
    {
        return m_position_ref;
    }

    /*!
     * @brief This function returns a reference to member position_ref
     * @return Reference to member position_ref
     */
    eProsima_user_DllExport std::array<double, 12>& position_ref()
    {
        return m_position_ref;
    }


    /*!
     * @brief This function copies the value in member torque_ref
     * @param _torque_ref New value to be copied in member torque_ref
     */
    eProsima_user_DllExport void torque_ref(
            const std::array<double, 12>& _torque_ref)
    {
        m_torque_ref = _torque_ref;
    }

    /*!
     * @brief This function moves the value in member torque_ref
     * @param _torque_ref New value to be moved in member torque_ref
     */
    eProsima_user_DllExport void torque_ref(
            std::array<double, 12>&& _torque_ref)
    {
        m_torque_ref = std::move(_torque_ref);
    }

    /*!
     * @brief This function returns a constant reference to member torque_ref
     * @return Constant reference to member torque_ref
     */
    eProsima_user_DllExport const std::array<double, 12>& torque_ref() const
    {
        return m_torque_ref;
    }

    /*!
     * @brief This function returns a reference to member torque_ref
     * @return Reference to member torque_ref
     */
    eProsima_user_DllExport std::array<double, 12>& torque_ref()
    {
        return m_torque_ref;
    }


    /*!
     * @brief This function copies the value in member current_offset
     * @param _current_offset New value to be copied in member current_offset
     */
    eProsima_user_DllExport void current_offset(
            const std::array<double, 12>& _current_offset)
    {
        m_current_offset = _current_offset;
    }

    /*!
     * @brief This function moves the value in member current_offset
     * @param _current_offset New value to be moved in member current_offset
     */
    eProsima_user_DllExport void current_offset(
            std::array<double, 12>&& _current_offset)
    {
        m_current_offset = std::move(_current_offset);
    }

    /*!
     * @brief This function returns a constant reference to member current_offset
     * @return Constant reference to member current_offset
     */
    eProsima_user_DllExport const std::array<double, 12>& current_offset() const
    {
        return m_current_offset;
    }

    /*!
     * @brief This function returns a reference to member current_offset
     * @return Reference to member current_offset
     */
    eProsima_user_DllExport std::array<double, 12>& current_offset()
    {
        return m_current_offset;
    }



private:

    std::string m_frame_id;
    uint32_t m_sequence_id{0};
    double m_timestamp{0.0};
    std::array<double, 12> m_kp_torque{0.0};
    std::array<double, 12> m_ki_torque{0.0};
    std::array<double, 12> m_kd_torque{0.0};
    std::array<double, 12> m_kp_position{0.0};
    std::array<double, 12> m_ki_position{0.0};
    std::array<double, 12> m_kd_position{0.0};
    std::array<double, 12> m_current_ref{0.0};
    std::array<double, 12> m_position_ref{0.0};
    std::array<double, 12> m_torque_ref{0.0};
    std::array<double, 12> m_current_offset{0.0};

};

#endif // _FAST_DDS_GENERATED_ECAT_ROBOT_REF_HPP_


