// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file test.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__TEST_HPP
#define FAST_DDS_GENERATED__TEST_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TEST_SOURCE)
#define TEST_DllAPI __declspec( dllexport )
#else
#define TEST_DllAPI __declspec( dllimport )
#endif // TEST_SOURCE
#else
#define TEST_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TEST_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure TestMsg defined by the user in the IDL file.
 * @ingroup test
 */
class TestMsg
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TestMsg()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TestMsg()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TestMsg that will be copied.
     */
    eProsima_user_DllExport TestMsg(
            const TestMsg& x)
    {
                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TestMsg that will be copied.
     */
    eProsima_user_DllExport TestMsg(
            TestMsg&& x) noexcept
    {
        m_data = x.m_data;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TestMsg that will be copied.
     */
    eProsima_user_DllExport TestMsg& operator =(
            const TestMsg& x)
    {

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TestMsg that will be copied.
     */
    eProsima_user_DllExport TestMsg& operator =(
            TestMsg&& x) noexcept
    {

        m_data = x.m_data;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x TestMsg object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TestMsg& x) const
    {
        return (m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x TestMsg object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TestMsg& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member data
     * @param _data New value for member data
     */
    eProsima_user_DllExport void data(
            double _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function returns the value of member data
     * @return Value of member data
     */
    eProsima_user_DllExport double data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport double& data()
    {
        return m_data;
    }



private:

    double m_data{0.0};

};

#endif // _FAST_DDS_GENERATED_TEST_HPP_


