network:
  #protocol: zipc
  #hostname: /tmp/ecat_master
  
  protocol: iddp #tcp #iddp #udp
  hostname: localhost #10.240.23.30 #localhost #192.168.99.10 #192.168.9.99 #10.240.22.49
  port: 5000 #54321(UDP)
  timeout: 1000

period_ms: 1
logging: false # file stored in /tmp
auto-start: true

control:
  motor_config_path: ${PWD}/motor_config/hyqreal3/hyqreal3_pos3b.yaml
  id_map_path: &id_map_path '/home/embedded/dls_ws/src/ec_dds/config/id_map/hyqreal3/hyqreal3_id_map.yaml' 
  #imu_id: [102]
  #ft_id: [110,111]
  #pow_id: [201]
  #valve_id: [120]
  #pump_id: [202]