joint_map: # electric motors
  1: leg_1_joint_1
  2: leg_1_joint_2
  3: leg_2_joint_1
  4: leg_2_joint_2
  5: leg_3_joint_1
  6: leg_3_joint_2
  7: leg_4_joint_1
  8: leg_4_joint_2


ecat_to_hal_id_map:
  1 : 0
  2 : 1
  120: 2 #valve
  3 : 3
  4 : 4
  121: 5 #valve
  5 : 6
  6 : 7
  122: 9 #valve
  7 : 9
  8 : 10
  123: 11 #valve