#############################
# LEG 1 
#############################
leg_1_joint_1:
  motor_type: HHCM #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x3B
  # gains: [200.0,0.0,10.0,0.0,0.0] # advr [200.0,0.0,10.0,0.0,0.0]
  gains: [9.0,4.907,0.02,0.0,0.0]  # circulo
  


leg_1_joint_2:
  motor_type: HHCM #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]

#############################
# LEG 2
#############################
leg_2_joint_1: # electric motor in the current settings is this joint
  control_mode: 0x3B #0x3B position, 0x71 velocity control, impedance mode 0xD4, current control 0xCC (ADVR driver)
  # control_mode: 0x3B //position, 0x71 velocity control, only torque controller 0xD4, current control 0xCC  (synapticon driver)
  gains: [0.0,0.0,0.0,0.0,0.0] # kp, ki, kd, 0, 0 //position and velocity control
  # stiffness, damping impendance control, tau_kp, tau_ki, tau_kd when impedance control in cascade with torque control
  

leg_2_joint_2:
  motor_type: HHCM #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]

#############################
# LEG 3
#############################
leg_3_joint_1:
  motor_type: HHCM #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]
  
leg_3_joint_2:
  motor_type: HHCM #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]

#############################
# LEG 4
#############################
leg_4_joint_1:
  motor_type: HHCM #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]
  
leg_4_joint_2:
  motor_type: HHCM #allowed HHCM, Circulo, FlexPro, default HHCM
  brake_present: false
  control_mode: 0x3B
  gains: [200.0,0.0,10.0,0.0,0.0]
